### ISSUE TITLE
Multiple Webcam objects for front and rear camera on same screen

### ISSUE THREAD

**Issue by EvgenyMuryshkin** [mozmorris/react-webcam#100]
Hi,
I am trying to show both front and rear cameras from laptop side by side.
```
<Webcam 
    ref={r => this.setRef(r)}
    audio={false}
    height={400}
    screenshotFormat="image/jpeg"
    width={535}
    videoConstraints={
        {
            deviceId: "a83e6286959ad30929fb609ccb444862ff00231b9590b55e3d764d6517e5b3e2"
        }
    }
/>

<Webcam 
    audio={false}
    height={400}
    screenshotFormat="image/jpeg"
    width={535}
    videoConstraints={
        {
            deviceId: "8948c4a9a163d604888135b82bc713c651cbc45d32c040a181062b2400f164de"
        }
    }
/>
```
Each component individually works fine, but when they are together - first one wins and both component displays same stream.

Do you have any suggestions on how this can be done?

Thanks,
Regards,
Evgeny

**Comment by mozmorris** [comment]
@EvgenyMuryshkin I believe this is a hardware restriction and will depend on your device. I've never seen this working despite trying it on various phones and laptops.
