### ISSUE TITLE
MediaStream.stop() is deprecated

### ISSUE THREAD

**Issue by kreba** [mozmorris/react-webcam#103]
Thank you for putting this nice library out there! :heart:

When unmounting the webcam, the following warning appears in the JavaScript console:

> MediaStream.stop() is deprecated and will soon be removed. Use MediaStreamTrack.stop() instead.

**Comment by mozmorris** [comment]
@kreba what browser is this in?

**Comment by kreba** [comment]
@mozmorris thanks for the fast response!

This was in **Firefox 61**.0.1 (64-bit) on Ubuntu 18.04
Also tried it in Chromium and got no such warning.

**Comment by mozmorris** [comment]
@kreba thank you. Will take a look.

**Comment by mozmorris** [comment]
Fixed in #486b459
