### ISSUE TITLE
videoConstraints property not accessible

### ISSUE THREAD

**Issue by scannillo** [mozmorris/react-webcam#104]
Hello. I cannot access the videoConstraints property in my code, however I see it written in the framework. The autocomplete shows 'videoSource' but not 'videoConstraints', while videoSource is NOT a prop in the framework. I am confused and would like help on accessing this to change my user facing camera. Thanks!

Property` 'videoConstraints' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Webcam> & Readonly<{ children?: ReactNode; }> & Readonly<WebcamProps>'

**Comment by mozmorris** [comment]
This is unrelated to this project, sorry.
