### ISSUE TITLE
rear camera not triggered when <Webcam /> properly configured

### ISSUE THREAD

**Issue by hyphaene** [mozmorris/react-webcam#108]
Hi,

I'm displaying the component in an app, but for an unknown reason I can't access to the rear cam, even though I properly configured it according to the README.md and the mozilla section it refers to .

Here is my component declaration 

```javascript
const MyComponent extends Component {
     webcam = createRef();
     render() {
                <Webcam
                    audio={false}
                    height={350}
                    ref={this.webcam}
                    screenshotFormat="image/jpeg"
                    width={500}
                    videoConstraints={{
                        facingMode: 'environment',
                    }}
                />
    }
)

```

I use Chrome version 69

Thanks !

**Comment by mozmorris** [comment]
@hyphaene have you tried this approach:

```js
class App extends React.Component {
  render() {
    const videoConstraints = {
      facingMode: { exact: "environment" }
    };

    return <Webcam videoConstraints={videoConstraints} />;
  }
}
```

What hardware are you using?

**Comment by hyphaene** [comment]
Hi @mozmorris ,

I tested the settings with my phone, whitout problem.

The issue was with a samsung tab, which I can't test on anymore.
Since it is working at least on one device, I assume it is most an hardware issue, then I'll close this issue.

Thanks for the reactivity !
