### ISSUE TITLE
Can I use onUserMedia to stream to server?

### ISSUE THREAD

**Issue by wiput1999** [mozmorris/react-webcam#109]
Hi, I'm planning to use onUserMedia to stream to a server can I do that?

**Comment by mozmorris** [comment]
See #30

**Comment by mozmorris** [comment]
No, that's just called once.

You can get access to the stream via a ref e.g `this.webcam.stream` when `this.webcam` is the ref to the component. Then see https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Recording_a_media_element for an implementation on how to record that stream.
