### ISSUE TITLE
Increase resolution of getSnapshot on iPhones

### ISSUE THREAD

**Issue by dbartholomae** [mozmorris/react-webcam#115]
Hi there!

Lovely project, very helpful! We are currently using it to take pictures, and on most devices it works fine, but on iPhones the screenshot has a worse resolution than the video stream. Anyone else encountered this problem? I didn't find a solution yet, but if someone can point me in the right direction, I would also be willing to contribute a PR.

Best,
Daniel

**Comment by dbartholomae** [comment]
Based on my current research the issue seems to be limited support of the canvas drawImage function on iOS. In the [docs](https://developer.apple.com/documentation/webkitjs/canvasrenderingcontext2d/1630282-drawimage) it is written that the source cannot be a video element (as in this case) - but the docs don't seem to be totally up to date, given that the video element works, just with reduced resolution. I've also read somewhere (but cannot find it anymore), that the canvas has limited space on iOS which would also make sense and explain the reduced resolution.

**Comment by mozmorris** [comment]
I wonder if #112 might help here.

**Comment by uwolfer** [comment]
#177 might also provides a workaround for this issue.
