### ISSUE TITLE
Mirror facing camera

### ISSUE THREAD

**Issue by PaulPCIO** [mozmorris/react-webcam#116]
Hi, are there any solutions to mirror the facing camera, current it is not a mirror stream of what the camera sees, would be nice to have a prop to be able to mirror the stream, i am forced to use scaleX(-1) but the actual image is still flipped so it does not help.

**Comment by PaulPCIO** [comment]
created a solution https://github.com/mozmorris/react-webcam/pull/117

**Comment by mozmorris** [comment]
Closed by #161
