### ISSUE TITLE
Does not work in iframe

### ISSUE THREAD

**Issue by steverob** [mozmorris/react-webcam#124]
I'm trying to load the webcam component from within an iframe and the video element just does not load. I don't see any errors in the console as well.

Here's a demo - https://codepen.io/anon/pen/wROKpQ. Here I'm embedding this app I've built on Glitch (https://glitch.com/edit/#!/tasty-peony) inside CodePen

**Comment by mozmorris** [comment]
How about this: https://codepen.io/mozmorris/pen/XoGXdR ?

**Comment by steverob** [comment]
Looks like Chrome has depricated cross-origin user-media access unless allowed by the parent. More here - https://dev.chromium.org/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

Needed to add `allow="camera;"` attribute in the iframe tag.

**Comment by steverob** [comment]
@mozmorris thanks I figured out the same :) :) I should dig in and try to debug more before posting issues! :D

**Comment by mozmorris** [comment]
Any chance you could add this to the README @steverob ?

**Comment by steverob** [comment]
@mozmorris sure!!! :)
