### ISSUE TITLE
Please use semantic versioning in the future

### ISSUE THREAD

**Issue by dbartholomae** [mozmorris/react-webcam#126]
When renaming `screenshotWidth` to `minScreenshotWidth` this broke our code. Please increment the breaking version (e. g. going from 1.0.4 to 2.0.0) when changing the interface of the component as projects will automatically install new packages as long as it is still in range (the breaking version remains the same).
You can find more information on semantic versioning here: https://semver.org/

Here's the breaking commit:
https://github.com/mozmorris/react-webcam/commit/3c7120e6074d3b683b9f503eaf6be3ff334db9a7

**Comment by mozmorris** [comment]
Ahhhhh my bad @dbartholomae - reviewed this and totally missed that `screenshotWidth` was going away.

**Comment by dbartholomae** [comment]
No worries. If help is needed with the repo I can also help out :)
