### ISSUE TITLE
Invalid constraint error message on Safari 11 with external webcam

### ISSUE THREAD

**Issue by nvizo** [mozmorris/react-webcam#128]
Webcam feed is not opening on Safari 11

**Comment by mozmorris** [comment]
Can you try this link: https://codepen.io/mozmorris/pen/JLZdoP

<img width="701" alt="screen shot 2019-02-19 at 17 26 36" src="https://user-images.githubusercontent.com/156303/53034667-9952db80-346b-11e9-8772-0a57bca85d9b.png">

**Comment by nvizo** [comment]
Yeah it's not showing any video feed in Safari. Chrome and Firefox are working fine. My camera is Logitech C922. I am also on Safari 11.1.

When I run the following snippet:

```
const handleError = function (e) {
  console.log(e)
}

ReactDOM.render(
  <Webcam 
    onUserMediaError={handleError}/>,
  document.getElementById('root')
);
```

I am getting OverconstrainedError.

**Comment by nvizo** [comment]
![`OverConstrained error`](https://i.imgur.com/enGLuVf.png)

**Comment by mozmorris** [comment]
Does it work with your internal webcam?

**Comment by nvizo** [comment]
I was testing on a Mac Mini with the Logitech C922. I just tried on my Macbook Pro running High Sierra and Safari 11.0.1. Same issue cannot open internal webcam.

**Comment by mozmorris** [comment]
Thanks for more info. Is it the same error message on the Macbook?

**Comment by nvizo** [comment]
Getting cross origin issues on the MacBook. Will continue looking into Safari this week. I'll let you know if I figure it out.

![Macbook Pro, Safari error messages](https://i.imgur.com/3gGA7Xn.png)

**Comment by mozmorris** [comment]
@nvizo are further info on this? Did you ever get it working?

**Comment by ischeck** [comment]
@mozmorris @nvizo  I have encountered the same problem,Maybe the reason is  "https"?

**Comment by Raraku** [comment]
Hi, was this issue ever fixed.
