### ISSUE TITLE
Camera change bug

### ISSUE THREAD

**Issue by BenQwOw** [mozmorris/react-webcam#129]
The API is not changing the camera the first time we change the deviceId.
After checking the API's code I detected that the requestUserMedia(), called in the componentWillUpdate, doesn't take into account the nextProps but the current, so after changing the constraints' deviceIds the recording shown is always from the wrong camera.
Can you fix this? Maybe using componentDidUpdate?
Thanks in advance.

**Comment by Bajoja** [comment]
I'm having the same problem :(

**Comment by mozmorris** [comment]
@BenQwOw @Bajoja PRs welcome 😄

**Comment by mozmorris** [comment]
Thank @BenQwOw.
