### ISSUE TITLE
Setting ref using functional component

### ISSUE THREAD

**Issue by chriswingler** [mozmorris/react-webcam#132]
How would you go about doing this?

I'm trying:

```
  let webcam;

  const setRef = webcamRef => {
    webcam = webcamRef;
  };
```

But can't get it to work.  ( Not sure if this is me not understanding refs or an issue with react-webcam and functional components )

**Comment by mozmorris** [comment]
You should use's React's `createRef`. Here's a demo https://codepen.io/anon/pen/MxqRgo

See the React docs for more info: https://reactjs.org/docs/refs-and-the-dom.html#refs-and-function-components
