### ISSUE TITLE
Cant get camera on local web page 

### ISSUE THREAD

**Issue by ben923** [mozmorris/react-webcam#133]
Hi everybody,
I'm using reactjs to make a web application like snapchat for a school project.
when i try react-webcam on codepen it's actually works and asking me to allow using camera on the browser but when i use it on my reactjs app then i go on my webpage and it don't ask to allow the cam and i cant get the datas,
somebody can help me or have the same issues?
thanks

**Comment by mozmorris** [comment]
Are you using https?
