### ISSUE TITLE
videoConstraints sizing

### ISSUE THREAD

**Issue by chloeseun** [mozmorris/react-webcam#134]
so my `<Webcam />` component is wrapped in a div that has `{width: 100vw, height 100vh}`

I want the video element to take after the parent div's dimensions and take up 100% of the screen view at all times including when browser is resized but it seems to have a certain ratio restriction.

Things I've tried:
- set `<Webcam />`'s height and width to 100%
- set `<Webcam />`'s height and width to 100vh and 100vw
- set **videoConstratin**'s height and width to auto (this does nothing)
- set **videoConstraint**'s height and width to 100% (this just gives me error)

I've come to a conclusion that it is coming from the **videoConstraint**'s settings but I am not sure how to overwrite it. 

Help would be appreciated thank you!

**Comment by qkreltms** [comment]
try this   
```js
     <Webcam
          audio={false}
          screenshotFormat="image/jpeg"
          videoConstraints={this.videoConstraints}
          ref={this.setRef}
          width="500"
          height="500"
           style={{
             height: "100vh",
             width: "100%",
             objectFit: "fill",
            position: "absolute"
          }}
        />
```

**Comment by mozmorris** [comment]
@chloeseun here's a demo: https://codepen.io/anon/pen/BezrMY
