### ISSUE TITLE
Get the image data without showing the preview window?

### ISSUE THREAD

**Issue by dhowe** [mozmorris/react-webcam#135]
Is it possible to grab image data without showing the preview window onscreen?

**Comment by mozmorris** [comment]
@dhowe perhaps just hide it offscreen? Example: https://codepen.io/anon/pen/OYEGZX?editors=0010

**Comment by dhowe** [comment]
Thanks, Grant! This does in fact work, though my original strategy of visually hiding the component (via css display) does not. Any idea why?

**Comment by mozmorris** [comment]
The canvas, in this case the screenshot, is generated from the video element. See https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

If that element is hidden, there's nothing to draw to the canvas from e.g the video element has no width, height, etc.
