### ISSUE TITLE
Passing ID to video element

### ISSUE THREAD

**Issue by ppozniak** [mozmorris/react-webcam#140]
Hello. It seems it doesn't accept ID props. Any particular reason why?
I would be happy to make a PR as it doesn't seem like lot of work.

**Comment by mozmorris** [comment]
@ppozniak PRs are always welcome. I think it would be better if all non-specific Webcam props are passed to the `video` element. I'll look at this shortly.

**Comment by mozmorris** [comment]
@ppozniak I have a PR (#143) open for this. Fancy testing it out?

**Comment by ppozniak** [comment]
Seems to work properly, good job

**Comment by mozmorris** [comment]
Thanks for reviewing @ppozniak 👍 

This isn't technically a breaking change but as I'm now passing all props to the underlying video element, there is a small risk this could unexpectedly break other peoples uses of the component. As such, I'll release this in a major bump shortly. I also need to update the README as well.

**Comment by mozmorris** [comment]
This has now been released @ppozniak, thank you for checking.
