### ISSUE TITLE
Support for Overlays

### ISSUE THREAD

**Issue by Kalaschnik** [mozmorris/react-webcam#144]
Is there any convenient way to add transparent overlays over the stream?
For example: Adding this crosshairs for aligning the person:
https://ui-ex.com/images/transparent-crosshair-sniper-6.png

**Comment by mozmorris** [comment]
Depends if you want it part of the final image/stream. If not, why not simply overlay your image? eg: https://codepen.io/anon/pen/XLyJzB

**Comment by Kalaschnik** [comment]
Oh, thanks @mozmorris! It should be indeed not part of the final stream. Thanks! This is super off topic now, but do you have any experience with the image cropping after the image has been captured? I basically need to get rid of the area outside of the circular crosshairs, that means I would end up with a round image and transparent regions to fill the square, something like this:
https://previews.123rf.com/images/bonumopus/bonumopus1603/bonumopus160300051/53181971-empty-white-paper-plate-vector-round-plate-illustration-on-transparent-background-plate-background-f.jpg

Feel free to just close this issue, I haven’t look into how to image edit yet.

**Comment by bharatgupta99** [comment]
What if I need to add an overlay to the final video?
