### ISSUE TITLE
Cannot set false for constraints

### ISSUE THREAD

**Issue by tung-eh** [mozmorris/react-webcam#145]
I want to grant video permission only, I expect that passing `false` as `audioConstraints` prop will make it works but it's not.

Maybe caused by this code
```
constraints.audio = audioConstraints || true;
```

The [MediaStreamConstraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints) API can receive a boolean as params for audio/video, so I think better check `audioConstraints` equal to `undefined` to return `true` instead of `||` like that

**Comment by mozmorris** [comment]
@tung-eh Thanks for the issue and for finding the offending code. I'll get a fix in.

**Comment by mozmorris** [comment]
@tung-eh also, you should be able to set the `audio` prop to `false` to achieve this as well.

**Comment by tung-eh** [comment]
@mozmorris I didn't notice that we have `audio` prop, just found the `audioContraints` then go directly here, thanks for pointing out
