### ISSUE TITLE
Use external USB Webcam as facingMode parameter

### ISSUE THREAD

**Issue by Kalaschnik** [mozmorris/react-webcam#147]
I’m working on a device which has 2 builtin cameras:

`facingMode: "user"` enables the front camera. And `facingMode: { exact: "environment" }` enables the back camera. However, I want to access my attached external USB Camera. I know it is possible since `enumerateDevices()` provides an array of all available devices, yet I think it is not implemented to choose a third option (aside from from the two mentioned modes)?

Here is demo page for all available sources:
https://webrtc.github.io/samples/src/content/devices/input-output/

This it how it looks if you got 3 camera devices:
![image](https://user-images.githubusercontent.com/9831678/61035828-26211600-a3c8-11e9-8e50-1315d7eaeb8f.png)

Or is this already possible? Thanks for any help on this!

**Comment by mozmorris** [comment]
It's possible to pass in a `deviceId` using the video constraints: see https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints
