### ISSUE TITLE
Detect when there is no camera

### ISSUE THREAD

**Issue by jpreecedev** [mozmorris/react-webcam#151]
I'd like to display an error message when the device has no webcam/it is disabled/turned off.  Can you recommend how to do this?

**Comment by mozmorris** [comment]
@jpreecedev in this instance, the function you pass as the `onUserMediaError` prop should be invoked. The same would apply if the user denied permission.

Does this work for you?

**Comment by jpreecedev** [comment]
makes sense.  thanks.

**Comment by akshayvenugopal07** [comment]
Hey @mozmorris 

Please help I know that react-webcam has issues rendering in webviews but if the camera fails the onUserMediaError is not being run in these webviews is there any way I can detect if the camera has error, its OK if the permission is denied or if there is an issue I just need to be notified somehow. Please help in any way you can its really critical for the application.

https://codepen.io/akshayvenugopal007/pen/QWyWLOX

**How to reproduce** 
Put the link in a  post it in social media (I sent it in Instagram chat and opened the link) which opened in a webview but the onMediaError was not thrown
