### ISSUE TITLE
this.ctx potentially null

### ISSUE THREAD

**Issue by obasilakis** [mozmorris/react-webcam#156]
Hi, recently we observed the following error occurring quite often: 

`TypeError: null is not an object (evaluating 'a.imageSmoothingEnabled=this.props.imageSmoothing')`

In the new version of the library, in react-webcam.tsx line 148
`if (ctx) {..}`

Could you please elaborate on whether this new check fixes the error mentioned above?

Ps. thanks for this great library :)

**Comment by mozmorris** [comment]
@obasilakis I believe so, have you tried the new version?

**Comment by obasilakis** [comment]
Thanks, we will give it a try and let you know.

In the meantime could you maybe walk me through the process that led you to this change? I'm asking because we weren't able to reproduce this error locally and don't quite understand where it comes from. We are worried this change will avoid the error, but not solve the problem because the app would just do nothing in that case.

**Comment by mozmorris** [comment]
The type checker made me aware that ctx could be null. It was coincidence you found this at runtime while I was also porting the code to TypeScript.

`getContext` can return `null`. Are you possible seeing this error during tests?

**Comment by obasilakis** [comment]
God bless TypeScript right?

Unfortunately I found the error in production logs and wasn't able to reproduce it with any tests.

In some of the cases it occurred after the user had already taken 4 pictures, so we can be sure it wasn't a browser issue. Any ideas on what could have caused it?

**Comment by mozmorris** [comment]
Was there any case where the user didn't take a picture?

**Comment by obasilakis** [comment]
So far I've only seen cases where the users have taken one or a couple of pictures before the error occurred.

**Comment by mozmorris** [comment]
@obasilakis I'm going to close this issue since I've believe the error is fixed. However, I do perhaps need to look at calling the error prop, then an error could be displayed to the user.
