### ISSUE TITLE
Show Camera permission modal when detected permission denied

### ISSUE THREAD

**Issue by ashleyongym** [mozmorris/react-webcam#160]
After declining the camera permission on the pop up modal, where it says **`Would like to access the Camera`**, is there a way to bring that modal back up, whenever detected permission denied?

**Comment by mozmorris** [comment]
@ashleyongym I don't believe so. You would need to inform the user to manually allow access to the camera/microphone.

**Comment by ashleyongym** [comment]
I see, even on a mobile web? Seems like it's gonna be difficult for the user to manually allow access on mobile phone. 

Also, to check for the permission denied, we have call this `onUserMediaError`?

**Comment by mozmorris** [comment]
@ashleyongym the experience on my own mobile is actually better than desktop - Safari iOS has a icon in the address bar which can be tapped to enable/disable the camera.

Whatever function you pass as the `onUserMedaError` prop will be called when permission is denied. See https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Exceptions for the types of error.

**Comment by ashleyongym** [comment]
Cool. Thanks for the help 😄👍
