### ISSUE TITLE
IE11 throws Syntax Error

### ISSUE THREAD

**Issue by Englund0110** [mozmorris/react-webcam#162]
I just updated to the latest version (1.1.1 => 3.1.0), but now it throws a "Syntax Error" in IE11. The error is thrown at line 118 in react-webcam.js. 

Any tips on how to resolve this?

**Comment by mozmorris** [comment]
That would be as I'm targeting es2017 for the output. I guess I should really target es5.

**Comment by mozmorris** [comment]
@Englund0110 I've published a new version, could you give it another try. Bare in mind it won't obviously render on ie11.

**Comment by Englund0110** [comment]
Thanks for the fast reply @mozmorris ! 

I have now tested the new version, and no errors was found when using IE11. It could be great if you could keep targeting es5 for a while. I know that the time will come sooner or later, but we are unfortunately still forced to support IE11 in our solution. If not, we are just sticking to the 1.1.1 version. :-)

**Comment by nonybrighto** [comment]
Please how do I make it work on IE 11? Is there a polyfill to make it work?

**Comment by mozmorris** [comment]
@nonybrighto the polyfill for IE11 uses Flash. There are no plans to support that here.
