### ISSUE TITLE
push to rtp protocol in aws media live

### ISSUE THREAD

**Issue by reckinam** [mozmorris/react-webcam#164]
I  want to do live streaming like facebook live chat,for that i am using aws media live .The input is feed through RTP_PUSH .Help that i need ,how to connect the media live and react webcam ?

**Comment by mozmorris** [comment]
@reckinam unfortunately we can't help you here. This issue tracker is for problems with the react-webcam library. You should post your question to StackOverflow where another developer may have already solved the same problem. Thanks.
