### ISSUE TITLE
Is there anyway i can stop recording the video output from react webcam ?

### ISSUE THREAD

**Issue by sedaplaksa** [mozmorris/react-webcam#166]
i tried ur previous solution this.webcam.stream.getVideotrack()[0]

But it doesnt work anymore

**Comment by mozmorris** [comment]
Do you have an example @sedaplaksa ?

**Comment by mozmorris** [comment]
Here's an example on CodePen: https://codepen.io/mozmorris/pen/ZEERQWz?editors=0110
