### ISSUE TITLE
getCanvas returns snapshot (instead of getting updated)

### ISSUE THREAD

**Issue by uwolfer** [mozmorris/react-webcam#167]
I've noticed that `getCanvas` draws the current video frame to the canvas and returns it. In my use case, it would be helpful if the returned canvas keeps updating. What's about adding a parameter `repaint` to `getCanvas` which enables repainting of the video while it is mounted (or adding a 2nd method like `getCanvasVideo` or something like that)?

Use case: I'd like to record the canvas to an animated gif using RecordRTC `GifRecorder` which is the only method I've found to record webcams on iOS Safari without using experimental Safari features.

**Comment by mozmorris** [comment]
@uwolfer `getCanvas` is only invoked when requesting a screenshot.

For your use case, you'd be better off getting access to the stream e.g `this.yourWebCamRef.stream` and passing that to `RecordRTC`

**Comment by uwolfer** [comment]
@mozmorris: Thanks for your feedback.

Yes, you are right, that would be a solution. Unfortunately, using `stream` in GifRecorder has some other limitations on iOS Safari (a fullscreen video preview app is started there). So I figured out this workaround using the canvas is a workaround for my use case.

**Comment by mozmorris** [comment]
It should be possible to keep calling `getCanvas` yourself then. `this.yourWebCamRef.getCanvas()`

**Comment by uwolfer** [comment]
Ok, you mean some type of polling? So I need to figure out a way how to call `getCanvas` whenever the recorder needs a new frame.

With my initial idea, it would work out of the box when passing the canvas to the recorder. But I think it should also be doable with your suggestion with some manual handling.

**Comment by mozmorris** [comment]
I'd say it will depend on the frame rate you require. Say you went for 20 fps, you could do something like https://codepen.io/mozmorris/pen/MWWBERo
