### ISSUE TITLE
iPhone dont show selfie cam

### ISSUE THREAD

**Issue by luizrfc** [mozmorris/react-webcam#168]
My application need the user take a picture with your selfie cam, Android works fine but iPhone show only the forward cam.

`const videoConstraints = {
width: 1280,
facingMode: 'selfie'
};`

` <Webcam
className={clsx(classes.webcam, 'flex justify-center')}
audio={false}
height='100%'
width='100%'
screenshotFormat='image/jpeg'
screenshotQuality={1}
videoConstraints={videoConstraints}
ref={(webcam) => { webcamRef = webcam }}
/>`

**Comment by mozmorris** [comment]
@luizrfc Thanks for your question.

If you check the api, you'll see that `selfie` is not a valid `facingMode` value. You should be using `user`.

https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode
