### ISSUE TITLE
Unable to run facial recognition on web cam on chrome android

### ISSUE THREAD

**Issue by sedaplaksa** [mozmorris/react-webcam#169]
Hi is there any reason why i am unable to run the cannot run the facial recognition software on the webcam only on chome android

**Comment by mozmorris** [comment]
@sedaplaksa thanks for opening this issue. Can you provide more details? An example of the code you are running would help us debug the issue.

**Comment by sedaplaksa** [comment]
So when running the webcam the video just keep running without executing my facial recognition code while on safari and desktop  it’s perfectly fine

**Comment by sedaplaksa** [comment]
There is no error message prompting me so I was wondering whether the camera is not compatible with chrome on Android

**Comment by mozmorris** [comment]
It's definitely compatible with Android (we have it running here) but perhaps there's an issue with your video constraints config?

As a test, can you open the following example on your Android and see if it works? https://codepen.io/mozmorris/pen/JLZdoP

**Comment by sedaplaksa** [comment]
Oo yeah that’s an error with my web hook my bad

**Comment by sedaplaksa** [comment]
Thanks for ur help btw

**Comment by mozmorris** [comment]
Not a problem 👍
