### ISSUE TITLE
Switch camera from user to environment (facingMode) on Android

### ISSUE THREAD

**Issue by tneels** [mozmorris/react-webcam#170]
Hello,

Is it possible to switch from front to back camera ?
I tried to change it using the state but nothing happen.

I don't know if it's a bug or a feature to ask for.

Thx for your help.

**Comment by mozmorris** [comment]
@tneels thanks for submitting this issue and that's a great question! 👍 

Here's an example: https://codepen.io/mozmorris/pen/mddvKBE?editors=0010

Let me know if it works for you.

**Comment by tneels** [comment]
Hey, 

Thanks for your very fast response !

I tried your codepen on multiple environments and actually the behaviors are really different from one to the other.
On **Iphone 8, v13.1.3** :
- **firefox v20.1** => we don't have access to the front and the back cam, and the browser don't ask for any authorization
- **safari** => it works perfectly

On my **onePlus 7 pro, android v10**
- **chrome v77.0** => access to the front cam, impossible to switch
- **firefox v68.2.1** => ask for front cam access > display cam view > click on switch button > ask for back cam access > don't switch cam view, and each time I click on the button, it ask for access but stay on the front cam.

**Comment by mozmorris** [comment]
Thanks @tneels for these data points.

On iOS (iphone) the camera will only work on Safari. This is because Firefox uses a Webview and getUserMedia isn't supported at the moment.

Re: Android. Could you try this example: https://codepen.io/mozmorris/pen/Exxrqjm?editors=0010

**Comment by tneels** [comment]
Yes I saw that for IOS. For "security reasons"...

Anyway, for the new tests :

onePlus 7 pro, android v10:
- Chrome v78.0: same as previously
- Firefox v68.2.1: ask for global cam authorization each time I try to switch, but actually it doesn't switch

I also tested on a pixel 2, android v10
- Chrome v78.0 => works perfectly
- Brave v1.5.1, chromium v78.0 => works perfectly

and on a pixel 3, android v10
- firefox v68.2.1 : always ask for authorization, work once, then click back to front cam, then don't work anymore

**Comment by mozmorris** [comment]
@tneels I think you will need to do some manual handling possibly. 

For example, `navigator.mediaDevices.getSupportedConstraints()` give you a list off supported constraints. It maybe that `facingMode` is _not_ supported. If that's the case it's possible to use the `deviceId` instead. See https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices on how to get the list of devices and their respective ids.

Here's another great overall guide: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints

**Comment by tneels** [comment]
Ok, thx.

I will investigate and I'll let you know here if I have any success.

Actually I will not care about firefox or other browsers as long as I use this in a webview.
Only chrome is relevant for android and safari for ios.

Anyway, huge thanks. You helped me a lot.

**Comment by mozmorris** [comment]
@tneels I'm going to close this issue now. Here's another example that uses the `deviceId` https://codepen.io/mozmorris/pen/KKwdOPO

**Comment by philgruneich** [comment]
I've been struggling with this issue for weeks, it is supposed to be very specific to Chrome for Android. You can start the getUserMedia with any facingMode, it will work. However, when you try to switch the facingMode it won't work for reasons I'm still trying to figure out.

**Comment by mozmorris** [comment]
@philgruneich it would be great if you could report back with any findings. The devices we've tested on work with the top example, but clearly there are issue on some others.

It would be good to finding out if this is a `getUserMedia` issue, or something within react-webcam that is causing it.

**Comment by philgruneich** [comment]
I won't be able to input much about it since we built a custom component to use ImageCapture. We used `getUserMedia` in 3 different pages. The first page had facingMode user, the second page had facingMode environment and would not load the MediaTrack. If we started the first page with facingMode environment, then everything would work. Therefore, we could only use the application in a single facingMode.

We noticed that we could toggle the facingMode if we were in the same page, so we moved our logic to take all photographs in the same page. In the end, we figured out that the issue was creating  multiple mediaStream objects, the Android just can't handle new mediaStreams and changing constraints properly. After only calling getUserMedia (and only stopping the tracks) when new constraints were to be applied that we solved our issue.

I don't think this is an issue for this library, since it works properly in other browsers and this scenario also plays out well in other Android devices, our issues were with a cheap Samsung tablet mostly. This is not even a getUserMedia issue, but how Chrome handles it in some Android devices.

**Comment by mozmorris** [comment]
Thanks @opapirnyk, great overview 👍

**Comment by tneels** [comment]
Hello @philgruneich , I didn't fully understand how you solved the issue. Is there any code example or something we can check ?

Thanks

**Comment by philgruneich** [comment]
@tneels We moved all the webcam logic to the same route because we created a new mediaStream with a custom hook, unfortunately, I can't share the code I wrote for it. Create a single MediaStream and work only on it, don't create additional MediaStream objects.

**Comment by tneels** [comment]
Thx @philgruneich , I finally figure out how to do it, thx to your reply. Here is a sample code to switch from front cam to back cam, or the inverse. 

```
flipCamera = () => {
        navigator.mediaDevices
            .getUserMedia(constraints)
            .then(stream => stream.getTracks().forEach(track => track.stop()))
            .then(() => this.setState(prevState => ({ isFacingMode: !prevState.isFacingMode })));
    };
```

This.state.isFacingMode is used to set up constraints in Webcam component props.

Hope it will help other devs in the same situation.

**Comment by keithpickering** [comment]
All the examples in this thread cause the latest version of Chrome for Android to become totally unresponsive. The whole browser freezes and requires a force close to get working again.

Are there any updates on this? I've tried changing the deviceId in the constraints with or without stopping all media streams first, with timeouts, etc.
