### ISSUE TITLE
[interesting] Show camera stream in modal

### ISSUE THREAD

**Issue by denis-n** [mozmorris/react-webcam#173]
Here is the old question:
https://github.com/mozmorris/react-webcam/issues/86

I'm using WebCam component in [React-Bootstrap modal](https://react-bootstrap.github.io/components/modal/)

When the modal window is closed before `onUserMedia` is executed, the camera on my laptop continues to work.

How to handle that? I was thinking about putting WebCam outside of modal (and maybe hide) and only show the stream in modal.

How can I show camera stream in modal?

**Comment by mozmorris** [comment]
@denis-n thanks for posting this detailed issue.

Have you got an example of this I can run and inspect?

As a suggestion, is it possible to stop the modal being closed until `onUserMedia` or `onUserMediaError` has been invoked?

**Comment by mozmorris** [comment]
Something like this: https://codepen.io/mozmorris/pen/NWPxqvd

**Comment by denis-n** [comment]
Thank you for the example. When I close the modal quickly the web camera continues to work.

I don't like the idea of delaying closing modal. Closing should be fast.

I would prefer to put WebCam component outside the modal and delay `unmounting` of it.

But for that I would need to show the video from web camera in modal.

How can it be done?

**Comment by mozmorris** [comment]
I understand closing should be fast but that's a trade-off for the UX. You're attempting to do two things at once (i. show modal, ii. load webcam) - perhaps you need to reconsider your UX and create something that is more user friendly.

How about delaying showing the modal until `onUserMedia` has been invoked? eg: https://codepen.io/mozmorris/pen/abzdWrx

If you're okay with mounting the component elsewhere in your app and hiding it, you can get access to the video stream `componentRef.stream` and pass this to your modal.

**Comment by denis-n** [comment]
I'm ok with hiding the WebCam component.

Sorry, how can I show the 'stream' content in modal? It's
