### ISSUE TITLE
Check hasGetUserMedia before accessing navigator.getUserMedia

### ISSUE THREAD

**Issue by uwolfer** [mozmorris/react-webcam#174]
It will fail when props update because there is no check for `hasGetUserMedia` (there is such a check in `componentDidMount`, which is correct IMHO). When props update and no user media is available, it will fail in `requestUserMedia`.

You might also want  to call `onUserMediaError` when `hasGetUserMedia` returns false (instead of just return null in `render`?

**Comment by mozmorris** [comment]
@uwolfer thank you for posting this issue, will create a PR and hopefully you'll have a chance to take it for a spin.

**Comment by uwolfer** [comment]
@mozmorris: Thanks. Sure, I can give it a try when it is ready.

Just looked into the code and wondered if there is a reason why you assign (polyfil) `navigator.getUserMedia` on https://github.com/mozmorris/react-webcam/blob/master/src/react-webcam.tsx#L168 and then access `navigator.mediaDevices.getUserMedia` on https://github.com/mozmorris/react-webcam/blob/master/src/react-webcam.tsx#L184. I'd have expected that you would access `navigator.getUserMedia` on L184.

You might also could extract to common parts (access of vendor specific APIs) of `hasGetUserMedia` and `requestUserMedia`.

**Comment by mozmorris** [comment]
Probably redundant code from years ago :-)

**Comment by uwolfer** [comment]
Following a small sample to reproduce this issue:

```tsx
navigator.getUserMedia =
      navigator.mediaDevices.getUserMedia =
      navigator.webkitGetUserMedia =
      navigator.mozGetUserMedia =
      navigator.msGetUserMedia = undefined;

function Base() {
  const [camera, setCamera] = React.useState("user");

  return (
    <div>
      <button onClick={() => setCamera("environment")}>
        Switch to env camera
      </button>
      <Webcam videoConstraints={{
        facingMode: camera
      }}/>
    </div>
  );
}
ReactDOM.render(
  <Base/>,
  document.getElementById('root')
);
```

**Comment by mozmorris** [comment]
4.0.1 should fix this issue. Can you try it?

**Comment by uwolfer** [comment]
@mozmorris Looks good! Thanks for the fast fix.

**Comment by mozmorris** [comment]
Great @uwolfer - also thanks again for the detailed issue with a reproducible example.

**Comment by uwolfer** [comment]
> Probably redundant code from years ago :-)

I think https://github.com/mozmorris/react-webcam/blob/master/src/react-webcam.tsx#L6-L8 and https://github.com/mozmorris/react-webcam/blob/master/src/react-webcam.tsx#L179-L183 can be removed if you feel like it. All modern browsers support the unprefixed version for some tie already: https://caniuse.com/#search=getUserMedia
