### ISSUE TITLE
Screenshots are mirrored like zigzag 

### ISSUE THREAD

**Issue by Hartha-aloufi** [mozmorris/react-webcam#179]
Hello

When I set mirrored props to true the screen shots behave incorrectly, first screenshot mirrored and the next one is not and so on.

<a href="https://codesandbox.io/s/gracious-sea-7gul2?fontsize=14&hidenavigation=1&theme=dark">
  <img alt="Edit 7gul2" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>

**Comment by Hartha-aloufi** [comment]
Fix here #180 , please give me feedback, it is my first PR to an open source project :)

**Comment by mozmorris** [comment]
@Hartha-aloufi thank you very much for posting this issue, along with an example - that's really great. Just reviewing the PR now - thanks for that too 😄

**Comment by mozmorris** [comment]
Wow, @Hartha-aloufi you nailed it. Many thanks.

Fix released in `4.0.2`, welcome to Open Source 👍 

<a href="https://codesandbox.io/s/damp-meadow-s54d9">
  <img alt="Edit 7gul2" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>

**Comment by Hartha-aloufi** [comment]
@mozmorris You are welcomed, Thank you you too for Awesome work.
