### ISSUE TITLE
Unable to set the muted property in the underlying video element

### ISSUE THREAD

**Issue by inigo-stripe** [mozmorris/react-webcam#182]
I've tried changing the `audio` (given this is what's passed to the underlying `video` element: https://github.com/mozmorris/react-webcam/blob/master/src/react-webcam.tsx#L364) but I'm unable to make `react-webcam` render a muted video element. Any ideas?

Could be related to https://github.com/facebook/react/issues/10389

**Comment by mozmorris** [comment]
Hello @inigo-stripe, thanks for posting this issue. I think you may have stumbled upon a bug in our code. 

I believe the `audio` prop's description and use is wrong 😬 

e.g if `<Webcam audio={false} />` the the video element would result in `muted="false"`, which is the the opposite of what one would expect, it should be `muted="true"`

This bug was introduced in [this commit](https://github.com/mozmorris/react-webcam/commit/4fe6d65ec4cc0d56524bc433daa4822e9d0f6469)

Here's an example where I set the `muted` attribute manually https://codepen.io/mozmorris/pen/vYEWYmN

I can hear the sound (in my case horrible feedback), how about you?

**Comment by mozmorris** [comment]
I'm guessing this hasn't come up before since having sound is probably an edge use case.

If the above example works for you, I will create a fix but switch the default value of `audio` to `false`.

**Comment by inigo-stripe** [comment]
Hi @mozmorris thanks for looking into this. In your [example codepen](https://codepen.io/mozmorris/pen/vYEWYmN), the resulting video element still doesn't have the `muted` attribute: `<video autoplay="" playsinline=""></video>`. I've tried several combinations of booleans for `audio` and `muted` and still no luck. I think this might be related to [this react bug](https://github.com/facebook/react/issues/10389).

**Comment by mozmorris** [comment]
@inigo-stripe I see what you mean. However for me, I don't hear any sound if I set `muted={true}`

**Comment by inigo-stripe** [comment]
@mozmorris Yes, I'm actually trying to only capture screenshots with no audio with the `muted`  attribute set in the `video` element in order to avoid issues with iOS blocking the autoplay (https://webkit.org/blog/6784/new-video-policies-for-ios/).

**Comment by mozmorris** [comment]
So ignoring the muted prop for now, does the most [basic example](https://codepen.io/mozmorris/pen/JLZdoP) not work for you on iOS? We have an iPhone (XS, iOS13) and iPad here and that example still works for us. The (example screenshot capture)[https://codepen.io/mozmorris/pen/gOOoqpw] works okay too.

**Comment by mozmorris** [comment]
@inigo-stripe did you get a chance to test this again using the above examples? We'd be very interested to hear if you're having problems on iOS.

**Comment by inigo-stripe** [comment]
Hi @mozmorris we've tested on iOS devices and it's working as expected. Seems like even without the `muted` property the video autoplays in Mobile Safari without issues.

**Comment by mozmorris** [comment]
Okay great 👍 I will close this but if you come across where could be an issue, please let us know and we can reopen.

**Comment by timhwang21** [comment]
Hi! I believe I've ran into this as well. I haven't found a concrete source, but it seems that Brave may refuse to autoplay unless the underlying video is muted.

There's some corroboration from MDN [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video): 

> In some browsers (e.g. Chrome 70.0) autoplay doesn't work if no `muted` attribute is present.

@mozmorris without discussing if allowing `muted` to be a separate prop, would you be open to a fix to the existing bug here https://github.com/mozmorris/react-webcam/blob/master/src/react-webcam.tsx#L385? Changing it to `muted={!audio}` should be sufficient for my (and OP's) needs. I can file a PR if so. Thank you!
