### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by vrochamaia** [mozmorris/react-webcam#183]
Hello, I'm getting the following issue while trying to use the library. 

`ReferenceError: navigator is not defined 
/node_modules/react-webcam/dist/react-webcam.js:149:5`

![Screen Shot 2020-01-07 at 09 35 22](https://user-images.githubusercontent.com/7724418/71895910-142eee80-3131-11ea-8367-0dd90184becb.png)

react-webcam: 4.1.0
webpack: 4.41.5
next.js: 9.0.5

Maybe Next.js is trying to run the lib on the server side? I'm not sure because the same code was working before and I don't know exactly when starts to break. :/

**Comment by uwolfer** [comment]
This might be related to my recent change: https://github.com/mozmorris/react-webcam/commit/ea5db843cb36b46b05b61fd0a7209035324cb666

`navigator` also got accessed before this change - but only when the component actually got rendered.

We could also add a check for `navigator`, but I'm not sure if this is the best solution.

**Comment by uwolfer** [comment]
@vrochamaia: When exactly do you get that reference-error? After starting a dev server? Does it still work in the browser?

**Comment by vrochamaia** [comment]
Yeah, it's on the development server. The error happens as soon as I call the component that imports the **react-webcam** library.

**Comment by uwolfer** [comment]
@vrochamaia: Do you get more details out of the trace? Is it because of some server side rendering?
You could try to downgrade to 4.0.0 and check if it also happens there - I'd assume it will not.

**Comment by vrochamaia** [comment]
Yeah, it might be because of the server side rendering, I'm not quite sure. The same thing happens with the 4.0.0 version. The full stack trace is this one:

> ReferenceError: navigator is not defined
> polyfillGetUserMedia
> /node_modules/react-webcam/dist/react-webcam.js:149:5
> Module../src/react-webcam.tsx
> /node_modules/react-webcam/dist/react-webcam.js:173:3
> __webpack_require__
> /node_modules/react-webcam/dist/react-webcam.js:30:30
> (anonymous function)
> /node_modules/react-webcam/dist/react-webcam.js:94:18
> (anonymous function)
> /node_modules/react-webcam/dist/react-webcam.js:97:10
> webpackUniversalModuleDefinition
> /node_modules/react-webcam/dist/react-webcam.js:3:20
> (anonymous function)
> /node_modules/react-webcam/dist/react-webcam.js:10:3
> Module._compile
> internal/modules/cjs/loader.js:688:30
> Module._extensions..js
> internal/modules/cjs/loader.js:699:10
> Module.load
> internal/modules/cjs/loader.js:598:32
> tryModuleLoad
> internal/modules/cjs/loader.js:537:12
> Function.Module._load
> internal/modules/cjs/loader.js:529:3
> Module.require
> internal/modules/cjs/loader.js:636:17
> require
> internal/modules/cjs/helpers.js:20:18
> react-webcam
> webpack:/external "react-webcam":1

And I also get this at the end:

![Screen Shot 2020-01-07 at 17 02 12](https://user-images.githubusercontent.com/7724418/71925296-80304780-316f-11ea-828c-120209a1b2c7.png)

**Comment by mozmorris** [comment]
Fixed in `4.1.1`

**Comment by vrochamaia** [comment]
Thank you. :)
