### ISSUE TITLE
Multiple webcams from different sources on one page issue

### ISSUE THREAD

**Issue by AmirAbrams** [mozmorris/react-webcam#185]
My Electron react application page uses three different webcams and when I change the webcam device source for one react-webcam component, it changes the other two component device sources. I was able to fix my issue by removing the loop in this line:
https://github.com/mozmorris/react-webcam/blob/73399381d17469f3011ff7a507a0db687c6efb38/src/react-webcam.tsx#L250

My video constraints look like this: 
```
let constraints: MediaTrackConstraints = {
        deviceId: deviceId,
        height: this.props.height,
        width: this.props.width
 };
```
I was going to create a pull request to remove that line but wanted to ask if there is a reason it enumerates through all the devices on the page?

**Comment by AmirAbrams** [comment]
See https://github.com/mozmorris/react-webcam/pull/186

**Comment by mozmorris** [comment]
Thanks @AmirAbrams. This is quite interesting and I'm very keen to test #186 out. I think the code to loop over the instances existed as I don't believe it was possible to show different webcam simultaneously. This clearly has changed :-)

**Comment by AmirAbrams** [comment]
I am going to close this issue since PR https://github.com/mozmorris/react-webcam/pull/186 is merged.
