### ISSUE TITLE
Wrong camera dimensions / ratio on Firefox

### ISSUE THREAD

**Issue by sschuchlenz** [mozmorris/react-webcam#188]
When I add a `react-webcam` component like so, the ratio is correct (280x280 px) on Chrome, but stays in (I guess) 16:9 on FF browsers:

`<Webcam
  ...
  height={280}
  width={280}
  ...
  minScreenshotWidth={1080}
  minScreenshotHeight={1080}
  ...
  videoConstraints={{
    width: 280,
    height: 280,
    ...
  }}
/>`

**Comment by mozmorris** [comment]
@sschuchlenz hopefully this https://codepen.io/mozmorris/pen/jOERXBy solves your problem.

I have specified the `aspectRatio` video constraints. Tested and working on `FF 72.0.2`
