### ISSUE TITLE
Webcam not requesting camera access

### ISSUE THREAD

**Issue by Spodeopieter** [mozmorris/react-webcam#190]
I am using docker-compose with express to host my already built webapp.
when running on my local machine everything works 100%, but when I run the docker images on a cloud VM (I have tested google cloud and Digital ocean) , then I am not getting a prompt to give webcam access.

**Comment by mozmorris** [comment]
Hello @Spodeopieter, thanks for posting a new issue. Unfortunately this won't be enough for us to debug the issue. Please add any extra information, such as a link to your application or the code you are using.

Please ensure you have read the README too as there are come common gotchas.

**Comment by Spodeopieter** [comment]
Also, the onUserMedia callback fires 3 times , but the onUserMediaError callback is not firing at all.

**Comment by mozmorris** [comment]
Are you serving the application over SSL? eg https://www.your-domain-hosted-on-do-or-gcloud.com

**Comment by Spodeopieter** [comment]
I am not serving it over ssl, but I have configured chrome to use 
chrome://flags/#unsafely-treat-insecure-origin-as-secure

**Comment by Spodeopieter** [comment]
Ok I just had to relaunch chrome , this fixed the problem. so ssl was the problem , thanks so much or the assistance.
