### ISSUE TITLE
Camera switch always falls back by one step

### ISSUE THREAD

**Issue by BrendanJiang** [mozmorris/react-webcam#191]
I was trying to use a dropdown to choose the camera among multiple choices. However the Webcam change in render() was always one step behind the dropdown selection change. Would highly appreciate if anyone could shed some light.

The skeleton of my code is shown below (typescript .tsx):

```typescript
class WebcamImplementation extends React.Component {
    constructor(props: EnrollmentTestCameraProp) {
        super(props);

        this.state = {
            dropdownItem: [],
            dropdownSelectedCameraData: '',
            cameraFound: false,
            errorElement: (<div />),
        };

        // ......

        this.refreshCameraList();
    }

    public render() {
        const videoConstraints = {
            deviceId: this.state.dropdownSelectedCameraData,
            width: WebCamImageWidth,
            height: WebCamImageHeight,
        };

        return !this.state.cameraFound
            ? (
                <div className="info-state-content-pane">
                    <div className="info-state-top  flex-3 error-state">
                        <Icon
                            className="info-state-icon"
                            iconName="Error" />
                    </div>
                    {this.loadErrorPage()}
                </div>
            ) :
            (
                <div className="content-area">
                    <div className="content-area-top">
                        <div className="phone-camera">
                            <div id="camera-area">
                                <div id="video-container">
                                    <Webcam
                                        audio={false}
                                        height={WebCamImageHeight}
                                        screenshotFormat="image/jpeg"
                                        screenshotQuality={1.0}
                                        videoConstraints={videoConstraints}
                                        width={WebCamImageWidth}
                                        onUserMedia={this.handleUserMedia}
                                        onUserMediaError={this.handleUserMediaError} />
                                </div>
                            </div>
                        </div>
                        <div className="dropdown-menu-center">
                            <Dropdown
                                label=''
                                options={this.state.dropdownItem}
                                selectedKey={this.state.dropdownSelectedCameraData}
                                onChange={this.onDropdownChange}
                            />
                        </div>
                    </div>
                </div>
            );
    }

    /**
     * Dropdown list change
     * @param event event
     * @param option dropdown option
     */
    private onDropdownChange(event?: React.FormEvent<HTMLDivElement>, option?: IDropdownOption) {
        this.setState({
            dropdownSelectedCameraData: option!.data,
        });
    }

    private refreshCameraList() {
        navigator.mediaDevices.enumerateDevices().then(mediaDeviceInfos => {
            const videoMediaDevices = mediaDeviceInfos.filter(mdi => mdi.kind === 'videoinput');
            videoMediaDevices.map(deviceInfo => this.state.dropdownItem.push({ key: deviceInfo.deviceId, text: deviceInfo.label, data: deviceInfo.deviceId }));
            if (videoMediaDevices.length > 0) {
                this.setState(
                    {
                        dropdownSelectedCameraData: this.state.dropdownItem[0].data,
                        cameraFound: true,
                    });
            } else {
                // No camera found
                this.setState(
                    {
                        cameraFound: false,
                        errorElement: <div></div>
                    });
            }
        });
    }
}

interface EnrollmentTestCameraState {
    dropdownItem: { key: string, text: string, data: string }[];
    dropdownSelectedCameraData: string;
    cameraFound: boolean;
    errorElement: JSX.Element;
}
```

The basic idea is to enumerate all the available cameras and initialize the dropdown list when loading page. Then when the user picks one from the dropdown, we set the selected camera's deviceId in videoConstraints and use this deviceId to pick the corresponding camera and get it mounted.

The following pic shows all the four cameras on my laptop, including three built-in cameras and an external USB one (the 3rd LifeCam Studio):
![allCamerasInDropdown_resized](https://user-images.githubusercontent.com/39136815/73019688-f15f3400-3dd8-11ea-826f-8f7b4e6f8379.PNG)

Here's the weird thing I've observed:
![step1_1stFrontSelected_resized](https://user-images.githubusercontent.com/39136815/73019965-7fd3b580-3dd9-11ea-83f0-601e98f1cc2c.PNG)![step2_2ndRearSelected_resized](https://user-images.githubusercontent.com/39136815/73019969-82360f80-3dd9-11ea-9524-fa89cf92de5e.PNG)![step3_3rdExternalSelected_resized](https://user-images.githubusercontent.com/39136815/73019975-84986980-3dd9-11ea-9e04-ea4d7857c417.PNG)
![step4_4thIRSelected_resized](https://user-images.githubusercontent.com/39136815/73019978-882bf080-3dd9-11ea-9294-f59a4a0c28cf.PNG)![step5_1stFrontSelectedAgain_resized](https://user-images.githubusercontent.com/39136815/73019982-8a8e4a80-3dd9-11ea-8b6b-c8acf8ad68b0.PNG)

As you can see, 
1) the first camera "Camera Front" was first chosen by the dropdown by default. And its stream was displayed correctly (pointing to the ceiling).
2) when I chose the 2nd "Camera Rear", the stream didn't change and it's still showing the front camera's ceiling picture.
3) when I chose the 3rd "LifeCam Studio", the stream got changed to the stream of the 2nd "Camera Rear", which was left one step behind.
4) in all the following steps, the stream always left one step behind the dropdown selection, i.e., it's always showing the previous selection's stream.
5) no matter what order I follow to switch the cameras, the pattern remains the same, i.e., the streaming is always showing the previous dropdown selection's camera.

Debugging in Chrome, I didn't see any obvious error. In render(), the deviceId value in videoConstraints always shows the correct one that I've just chosen in the dropdown. Thus I don't believe it's a dropdown issue.

I've also searched the past posts. For example, from #47 it looks like we don't have to unmount the old one before mounting a new camera. Some other discussion threads seemed to follow the same switching pattern such as:
[https://stackoverflow.com/questions/55000680/unable-to-switch-camera-front-to-rear-in-react-application-using-webrtc-mediad](url)
[https://www.twilio.com/blog/2018/04/choosing-cameras-javascript-mediadevices-api.html](url)
What am I missing here?

Could anyone please help me out? Thanks very much!

**Comment by mozmorris** [comment]
Hi @BrendanJiang - thanks for posting this issue with a code sample, that's always useful.

Could you try this basic example that allows selecting a device: https://codepen.io/mozmorris/pen/KKwdOPO?editors=0010

Does this example work for you?

At a glance, there's some patterns in your code that are a bit of a red flag eg:

```js
this.setState({
    dropdownSelectedCameraData: this.state.dropdownItem[0].data,
    cameraFound: true,
});
```

In your `setState` you're potentially using stale data: `this.state.dropdownItem[0].data`

I'd advise using the functional form for setState: eg

```js
this.setState(prevState => ({
    dropdownSelectedCameraData: prevState.dropdownItem[0].data,
    cameraFound: true,
}));
```

I'd highly recommend looking at the [CodePen example](https://codepen.io/mozmorris/pen/KKwdOPO?editors=0010) above to see how you might structure your code a little clearer.

**Comment by mozmorris** [comment]
Also please excuse me editing your code sample, it was simply to give it some more context. :-)

**Comment by mozmorris** [comment]
@BrendanJiang here's your example code but I've taken the liberty of simplifying it a little: https://codepen.io/mozmorris/pen/BayMepP?editors=0011

**Comment by BrendanJiang** [comment]
Thank you very much @mozmorris! Your example significantly simplified my logic. However, I'm still experiencing the same problem. To cross verify it, I tried on my desktop with two external USB cameras, and hit the same thing.

Here's my complete code without any masking-out, just FYI. And it'll be extremely helpful if you have other clues. Thanks again!

`import './styles/EnrollmentSite.scss';
import * as React from 'react';
import * as Webcam from 'react-webcam';
import { EnrollmentPageSteps, WebCamImageHeight, WebCamImageWidth } from '../../utils/enrollmentUtils';
import './assets/images/CameraOverlay.svg';
import { PrimaryButton } from 'office-ui-fabric-react/lib/Button';

export class EnrollmentTestCamera extends React.PureComponent<EnrollmentTestCameraProp, EnrollmentTestCameraState> {
    constructor(props: EnrollmentTestCameraProp) {
        super(props);

        this.state = {
            dropdownItems: [],
            selectedCamera: null,
        };

        this.onDropdownChange = this.onDropdownChange.bind(this);
        this.refreshCameraList = this.refreshCameraList.bind(this);

        this.refreshCameraList();
    }

    public render() {
        return (
            <div className="content-area">
                <div className="content-area-top">
                    <div className="phone-camera">
                        <div id="camera-area">
                            <div id="video-container">
                                {this.state.selectedCamera && (
                                    <Webcam
                                        audio={false}
                                        height={WebCamImageHeight}
                                        screenshotFormat="image/jpeg"
                                        screenshotQuality={1.0}
                                        videoConstraints={{
                                            deviceId: this.state.selectedCamera,
                                            width: WebCamImageWidth,
                                            height: WebCamImageHeight,
                                        }}
                                        width={WebCamImageWidth} />
                                )}
                            </div>
                            <img
                                id="overlay-circle"
                                src="dist/assets/CameraOverlay.svg" />
                        </div>
                    </div>
                    <div className="dropdown-menu-center">
                        <select onChange={this.onDropdownChange}>
                            <option>Please select</option>
                            {this.state.dropdownItems.map(device => (
                                <option
                                    key={device.deviceId}
                                    value={device.deviceId}>
                                    {device.label}
                                </option>
                            ))}
                        </select>
                    </div>
                </div>
                <div className="content-area-bottom">
                    <p className="photo-title">
                        {' '}
                        {this.props.title}
                        {' '}
                    </p>
                    <p className="photo-taking-reminder">
                        {this.props.paragraph}
                        {' '}
                    </p>
                    <PrimaryButton
                        allowDisabledFocus={true}
                        className="info-state-primaryBtn"
                        text={this.props.buttonText}
                        onClick={() => {
                            // Return the selected camera
                            this.props.callback(this.state.selectedCamera);
                            this.props.onPageNext(this.props.buttonAction);
                        }} />
                    <p className="photo-taking-reminder">
                        {' '}
                    </p>
                </div>
            </div>
        );
    }

    private onDropdownChange(event: { target: { value: any; }; }) {
        this.setState({
            selectedCamera: event.target.value,
        });
    }

    private refreshCameraList() {
        navigator.mediaDevices.enumerateDevices().then(mediaDeviceInfos => {
            const videoMediaDevices = mediaDeviceInfos.filter(mdi => mdi.kind === 'videoinput');
            this.setState({
                dropdownItems: videoMediaDevices,
            });
        });
    }
}

interface EnrollmentTestCameraProp {
    direction: EnrollmentPageSteps;
    onPageNext: Function;
    title: string;
    paragraph: string;
    buttonText: string;
    buttonAction: EnrollmentPageSteps;
    callback: Function;
}

interface EnrollmentTestCameraState {
    dropdownItems: MediaDeviceInfo[];
    selectedCamera: any;
}`

**Comment by mozmorris** [comment]
@BrendanJiang here's your example on CodePen, this time still in TypeScript: https://codepen.io/mozmorris/pen/povYqLL?editors=0011 - I've removed code that not needed for this demo.

This works for me, on mobile and desktop - the dropdown is in sync with the current camera.

**Comment by mozmorris** [comment]
Just to be clear, when you say "However, I'm still experiencing the same problem" is that using my examples, your own code, or both?

**Comment by BrendanJiang** [comment]
@mozmorris I was using your example, without any change. And with the updated example code, I'm still seeing it. It's highly likely it's related to some of my React setups. I'll dig further and let you know. Finally thank you so much again for your great help!
