### ISSUE TITLE
Is there a way to append the returned base64 to FormData?

### ISSUE THREAD

**Issue by kirasiris** [mozmorris/react-webcam#193]
I'm actually trying to implement this library into my project because it is too easy to set up(I give you a 15/10 rating; xD).

The thing that I want is to store that data into a const to save it into my database. Let's put it this way, I'm allowing the users to take pictures for the profile avatars.

This is my code that I currently have:
```
  const webcamRef = React.useRef(null);
  const capture = React.useCallback(() => {
    const imageSrc = webcamRef.current.getScreenshot();
  }, [webcamRef]);

  const onSubmit = async e => {
    e.preventDefault();
    const imageSrc = webcamRef.current.getScreenshot();
    const formData = new FormData();
    formData.append('avatar', imageSrc);
    console.log(formData);
    // editAvatar(formData, setUploadPercentage);
  };
```
Right now the console.log(formData) displays the FormData Object but it does not contain any value in the append field which is the reason is giving me troubles. This is the console.log():
[Click here](https://ibb.co/BsWN59J)

After playing with it I decided to append the string into an input value but it is still not working:
```
const imageSrc = webcamRef.current.getScreenshot();
    const input = (document.getElementById('avatar-input').value += imageSrc);
    setFormData({ avatar: input });
    console.log(formData);
    setFormData({ ...formData, [e.target.name]: e.target.value });
```

**Comment by mozmorris** [comment]
@kirasiris thanks for posting this but I don't believe this is an issue with the component.

If you need help, I would suggest posting this on Stackoverflow. It would also be easier to help if you recreated your example on CodePen.

**Comment by kirasiris** [comment]
My bad , I will delete the post then. Thanks for this cool component!.

**Comment by mozmorris** [comment]
@kirasiris if you can recreate your problem on CodeSandbox, CodePen, etc - I can take a closer look and provide some assistance.

**Comment by Vini98br** [comment]
`
  function dataURLtoFile(dataurl, filename) {
    var arr = dataurl.split(','),
        mime = arr[0].match(/:(.*?);/)[1],
        bstr = atob(arr[1]), 
        n = bstr.length, 
        u8arr = new Uint8Array(n);
        
    while(n--){
        u8arr[n] = bstr.charCodeAt(n);
    }
    return new File([u8arr], filename, {type:mime});
  }
`
 @kirasiris send your base64 as dataUrl to this function, and then, with the file returned, append to the form data

**Comment by kirasiris** [comment]
@Vini98br thank you so much for this!!!. I was just able to implement this feature!! xD.
