### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by formidable255** [mozmorris/react-webcam#195]
When saving the image from getScreenshot(), is there a way to get the resolution of the image from the webcam instead of the resolution in the UI. 

For example, my 1920x1080p webcam is displayed in a 300x300p UI. How can i retrieve the 1080p image instead of a 300p image?

**Comment by mozmorris** [comment]
You should be able to do with using the `videoContraints` and `forceScreenshotSourceSize` props. Here's an example: https://codepen.io/mozmorris/pen/GRgbroM?editors=0010

**Comment by formidable255** [comment]
> You should be able to do with using the `videoConstraints` and `forceScreenshotSourceSize` props. Here's an example: https://codepen.io/mozmorris/pen/GRgbroM?editors=0010

Is there anyway to use videoconstraints 300 width 300 height and have forceScreenshotSourceSize take a 1080p?

**Comment by mozmorris** [comment]
Firstly, you should be aware that using width/height videoConstraints to obtain a 1:1 aspect ratio produces inconsistent results across different browsers and devices. For example, some browsers crop and centre, others don't crop but resize and leave blank space.

There is the `aspectRatio` video constraint but this is not yet supported widely.

May I ask what you are trying to achieve before suggesting other ideas?

**Comment by formidable255** [comment]
What I am trying to achieve is to take a picture with the webcam and get an image back in the camera's resolution; could be 1080p, 720p, etc. Then i will use that photo for further work. It seems that images i get back are stuck at 640x480p even with different cameras.

**Comment by formidable255** [comment]
It seems i may have found a solution. I specified a preference of 1920x1080p in the getUserMedia function.

**Comment by RezaZR** [comment]
> It seems i may have found a solution. I specified a preference of 1920x1080p in the getUserMedia function.

I have same problem, do you use react-webcam and you combine with getUserMedia? Because mine doesn't work. How you did that?

**Comment by mwijaya3** [comment]
> It seems i may have found a solution. I specified a preference of 1920x1080p in the getUserMedia function.

Can you provide an example?

**Comment by consultantvengage** [comment]
how to view the video stream in a circular window. I am using react with tailwind css

**Comment by rafaelEsparta** [comment]
Almost 3 years i have the solution guys..
Take the photo not using react-webcam just using a simple take picture function

**Comment by IayushCoderJOD** [comment]
Bhai Use Copilot, it solved this issue in 3 mins

**Comment by OArnarsson** [comment]
@IayushCoderJOD you mind sharing how you achieved this?
A webcam feed of say 720p but taking a 4K photo?

This is especially useful on low powered devices with good cameras. The camera feed lags over 720p but it can produce over 4k images. Hence the need for a lower quality feed but higher quality photos.
