### ISSUE TITLE
"minScreenshotWeight" react sending Warning on this

### ISSUE THREAD

**Issue by Sim3Xx** [mozmorris/react-webcam#196]
Hello Dear Webcam Developers,

I installed your library in my react Project, so good so far. But when i add the property "minScreenshotWeight" or "minScreenshotHeight" to the "Webcam Element", I get an error from React that it could not recognize the "minScreenshotWeight" property, it seems like React wants custom props to be in lowercase.

Visible in the following picture.:
![image](https://user-images.githubusercontent.com/46575728/73829583-831c6780-4803-11ea-82b8-9cc856d7011e.png)

PS: This Error message is actually only showing, when you set the **"minScreenshotWeight"** Property. React has no problem with the "minScreenshotHeight". Somehow 😄

**Comment by mozmorris** [comment]
You've got a typo @Sim3Xx, the prop is named `minScreenshotWidth`
