### ISSUE TITLE
DOM exception: NotReadableError - Could not start video source

### ISSUE THREAD

**Issue by carlosalvarez91** [mozmorris/react-webcam#198]
In a desktop browser (Chrome and Brave) works fine,
however on **android Chrome it just crashes**, especially in a standalone PWA, sometimes it doesn't crash on a chrome tab
It seems like it's not a problem of this package itself, I've been trying react-html5-camera-photo  and it throws the same error.
I've been trying to stop all tracks in an active stream before acquiring a new one on init component like this:
```
navigator.getUserMedia({audio: false, video: true},
        function(stream) {
             stream.getTracks().forEach(track=>{
               track.stop()
             })
        },
        function(error){
            console.log('getUserMedia() error', error);
          }
);
```
but it still throws this exception when opening the camera
**DOM exception: NotReadableError**
I'm testing it in https context
Any solutions ?
Thanks

**Comment by mozmorris** [comment]
This sounds like your device is in use by another process.
