### ISSUE TITLE
Capture a snapshot without showing the video feedback

### ISSUE THREAD

**Issue by paulopacitti** [mozmorris/react-webcam#199]
- I'm making a facial recognition unlock feature in a project I'm working on it. I'd like to know if it's possible to take a snapshot without showing the video feedback.
- I already tried wrapping a `display: none` in the `className`, but I couldn't take a snapshot, it displays a empty string :/ Can someone help with this please?

**Comment by mozmorris** [comment]
Capturing works by taking the current video element, rendering it to canvas, and creating a base64 string from it. If you hide the video using `display: none`, this will remove it from the dom and you won't be able to render it to canvas.

You should however be able to render the video element off screen. eg. `transform: translateX(-10000px)` or `position: absolute; left: -10000px;`

**Comment by paulopacitti** [comment]
Hmmm, now I understood how it works. Thanks for explaining ✨
I figured out another way of rendering the video element off screen:
```css
.camera {
  position: absolute;
  z-index: -1;
}
`````
