### ISSUE TITLE
Webcam on Ant Design modal does not show on mobile device

### ISSUE THREAD

**Issue by kakariko-village** [mozmorris/react-webcam#201]
Hi i am using react webcam with Ant Design (https://ant.design/components/modal/). My goal is display webcam when toggle a modal. It works normally on PC but on real mobile device, react webcam does not show on the modal. There's also no "access camera permission" warning on mobile. Here is my code:

App.js:
```
import React from 'react';
import { Button } from 'antd';
import WebcamModal from './WebcamModal';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      showModal: false,
    };
    this.showModal= this.showModal.bind(this);
    this.closeModal= this.closeModal.bind(this);
  }

  showModal = () => {
    this.setState({showModal: true})
  };

  closeModal = () => {
    this.setState({showModal: false})
  };

  render() {
    return(
      <div className='wrapper'>
        <Button type="primary" onClick={this.showModal}>Open Webcam</Button>
        <WebcamModal
          isShow={this.state.showModal}
          closeModal={this.closeModal}
        />
      </div>
    )
  }
};

```

WebcamModal:

```
import React from 'react';
import { Modal, Button } from 'antd';
import Webcam from "react-webcam";
import 'antd/dist/antd.css';
import './App.css';

export default class WebcamModal extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
        this.closeModal= this.closeModal.bind(this);
    }

    closeModal = () => {
        this.props.closeModal();
    };
    render() {
        return(
            <div className='webcam-wrapper'>
                <Modal
                    visible={this.props.isShow}
                    centered
                    closable={false}
                    footer={false}
                    onCancel={this.props.closeModal}
                    bodyStyle={{ padding: 14 }}
                    className='webcam-modal'
                >
                    {this.props.isShow
                        ?
                        <div className='content'>
                            <Webcam />
                            <Button type="primary" onClick={this.closeModal} style={{marginTop: 20}}>Close</Button>
                        </div>
                        : ''
                    }

                </Modal>
            </div>
        )
    }
};

```

**Comment by mozmorris** [comment]
@kakariko-village thanks for this report. Before investigating further, could you check if this demo works on the mobile device you mention?

https://codepen.io/mozmorris/pen/JLZdoP

**Comment by kakariko-village** [comment]
> @kakariko-village thanks for this report. Before investigating further, could you check if this demo works on the mobile device you mention?
> 
> https://codepen.io/mozmorris/pen/JLZdoP

Hi @mozmorris  , your example works on tablet and smartphone. Funny thing is that react-webcam somehow does not work with other modals on tablets  and mobile devices ( I tested on iPad 2018 and iPhone 11  Pro Max). Here's the example, i use modal from React Boostrap  and react webcam does not show on mobile devices too (PC works normally):

App.js:
```
import React from 'react';
import { Button } from 'antd';
import WebcamBoostrapModal from './WebcamBoostrapModal';
import 'bootstrap/dist/css/bootstrap.min.css';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      showModal: false,
    };
    this.showModal= this.showModal.bind(this);
    this.closeModal= this.closeModal.bind(this);
  }

  showModal = () => {
    this.setState({showModal: true})
  };

  closeModal = () => {
    this.setState({showModal: false})
  };

  render() {
    return(
      <div className='wrapper'>
        <Button type="primary" onClick={this.showModal}>Open Webcam</Button>
        <WebcamBoostrapModal
            isShow={this.state.showModal}
            closeModal={this.closeModal}
        />

      </div>
    )
  }
};

```

WebcamBoostrapModal.js:
```

import React from 'react';
import { Modal } from 'react-bootstrap';
import Webcam from "react-webcam";
import 'bootstrap/dist/css/bootstrap.min.css';
import './App.css';

export default class WebcamBoostrapModal extends React.Component {
    constructor(props) {
        super(props);
        this.state = {};
        this.closeModal= this.closeModal.bind(this);
    }

    closeModal = () => {
        this.props.closeModal();
    };
    render() {
        return(
            <div className='webcam-wrapper' >
                <Modal show={this.props.isShow} onHide={this.closeModal}>
                    <Modal.Header closeButton>
                        <Modal.Title>Modal heading</Modal.Title>
                    </Modal.Header>
                    <Modal.Body>
                        <Webcam />
                    </Modal.Body>
                </Modal>
            </div>
        )
    }
};

```

**Comment by mozmorris** [comment]
Here's a another demo that uses Bootstrap Modal. Tested on iPhone XS

https://codepen.io/mozmorris/pen/NWPxqvd

**Comment by kakariko-village** [comment]
> Here's a another demo that uses Bootstrap Modal. Tested on iPhone XS
> 
> https://codepen.io/mozmorris/pen/NWPxqvd

Nice, your example work on my iOS devices. I will try to apply to my project tomorrow. Since i don't use React hook, do you know what wrong with my examples using class component?

**Comment by mozmorris** [comment]
I can’t see anything obvious, but it should be pretty straight forward to convert my example to use a class based component.

**Comment by kakariko-village** [comment]
> Here's a another demo that uses Bootstrap Modal. Tested on iPhone XS
> 
> https://codepen.io/mozmorris/pen/NWPxqvd

Hi @mozmorris , after doing some research, i guess that the problem is  the lack of https domain. Your example run on a https domain (https://codepen.io/) so browsers from mobile device can load the react webcam. I did copy, paste and run your code on local machine and my mobile devices still cannot load the react webcam with local IP Address. On iOS, Safari return the error message "Error: getUserMedia is not implemented in this browser" when i log the error with onUserMediaError. Can you confirm my concern about https required for react webcam?

**Comment by mozmorris** [comment]
`Note: Browsers will throw an error if the page is loaded from insecure origin. I.e. Use https.`

Top of the README 😉
