### ISSUE TITLE
Need to reduce captured image file size using configuration

### ISSUE THREAD

**Issue by yashp98** [mozmorris/react-webcam#202]
We trying to caputre screen shot using this plugin with following react code
**const screenshot = webcamRef.current.getScreenshot();**

I am able to get screenshot object correclty but issue is that size for that is approx **11MB - 15MB** which seems very high.Is there cofiguration to reduce this object size.I need to reduce size for this object to approx **2MB**.

**Comment by mozmorris** [comment]
Please see the `screenshotFormat` and `screenshotQuality` props.

**Comment by yashp98** [comment]
I have put this value and image size is not reduzing.
 screenshotQuality={0.1}
screenshotFormat="image/jpeg"

**Comment by yashp98** [comment]
screenshotQuality={0.1}
screenshotFormat="image/jpeg"
I have update above value but image size is not reduzing.
What should be next? 
Can you guide me on this?

**Comment by mozmorris** [comment]
@yashp98 here is an example: https://codepen.io/mozmorris/pen/KKpRLBd?editors=0110

Try changing the `screenshotQuality` prop, you will see the reduction in image quality and subsequent file size. File size can be checked in the devtools network panel.
