### ISSUE TITLE
Add loading when initialising camera

### ISSUE THREAD

**Issue by handhikadj** [mozmorris/react-webcam#204]
AFAIK, the camera mounting process is async. so what is the workaround to add the loading state when initialising the camera?

**Comment by mozmorris** [comment]
@handhikadj you should be able to imply loading when the component is mounted. Loading is finished when `onUserMedia` or `onUserMediaError` is called.

**Comment by handhikadj** [comment]
okay thank you for the workaround

**Comment by RoryOfByrne** [comment]
@mozmorris I want to render a general introduction/logo component while I wait for permissions, and then render the Webcam once I have permissions. Is this possible, or should I handle permissions myself and then render the Webcam afterwards?

**Comment by mozmorris** [comment]
@RoryOfByrne this seems perfectly fine to me :-)
