### ISSUE TITLE
Getting low quality image

### ISSUE THREAD

**Issue by yashp98** [mozmorris/react-webcam#206]
Hello sir we using this plugin in our application we used to get good quality image with size 8MB to 10 MB.We using folloing option to get image

**<StyledWebCam
				audio={false}
				ref={webcamRef}
				screenshotQuality={1}
				screenshotFormat="image/jpeg"
				videoConstraints={{
					facingMode: 'environment'
				}}
			/>**

but now we getting very low quality image with image size 183KB.How can we improve image quality?

**Comment by mozmorris** [comment]
@yashp98 this is the same question as you have already posted in #202.

You need to use a value between `0` and `1`
