### ISSUE TITLE
onUserMediaError not invoked when webcam stops

### ISSUE THREAD

**Issue by lowewenzel** [mozmorris/react-webcam#207]
Hey there, great library so far! I've been playing around with it, and noticed that the `onUserMediaError` is not thrown when a webcam is disconnected. The webcam view is still visible, but the view is all black.

I am able to replicate this using Mac OS `sudo killall VDCAssistant` to turn off the camera system. I'm assuming this also happens with USB webcams as well (but could be mistaken).

**Comment by lowewenzel** [comment]
Sorry, didn't realize that #187 could possibly be related. Please close this if it could be linked to the same solution, but otherwise would like to keep this discussion open.

**Comment by lowewenzel** [comment]
Looks like a way to detect this is `MediaStream.active`... Played around with https://simpl.info/getusermedia/ which has global scope on `stream`, and `stream.active` becomes false once it loses a source. 

It's late night and I found a hacky solution to my problem, but hope this is seen by others incase they need it. I have a `useEffect` that checks every so seconds using `useInterval` on `webcamRef.current.stream.active`.

**Comment by mozmorris** [comment]
@lowewenzel I've been meaning to investigate this issue and finally got around to it.

The following example works for me: https://codepen.io/mozmorris/pen/dyYNYwd

**Comment by lowewenzel** [comment]
This works well for my cases, thank you!
