### ISSUE TITLE
Video constraints mixes width and height

### ISSUE THREAD

**Issue by cemozerr** [mozmorris/react-webcam#209]
I use react-webcam to take user-facing photos. Whatever width I specify gets used for height, and vice versa. For example, here is my videoConstraints and all the props I pass into the Webcam component: 
```
const videoConstraints = {
    height: 675,
    width: 900,
    facingMode: "user"
};

 <Webcam
  className="photoBox"
  forceScreenshotSourceSize={true}
  audio={false}
   ref={webcamRef}
   screenshotFormat="image/jpeg"
   videoConstraints={videoConstraints}
/>
```
With these settings, the screenshots I capture have dimensions: 675x900. So, width of 675px and height of 900px. I'm taking these screenshots using iOS Safari.

**Comment by mozmorris** [comment]
@cemozerr thanks for this report, will investigate shortly.

**Comment by mozmorris** [comment]
@cemozerr so I've had a look at this - you might need to give me some further details about the behaviour you were expecting.

Here's an example: https://codepen.io/mozmorris/pen/JjYzRpa?editors=0010

This uses the width and height constraints, and the `forceScreenshotSourceSize` gives a distorted image when I shoot in portrait.

**Comment by mozmorris** [comment]
It's worth mentioning that the constraints values are linked to the media devices capabilities i.e not all devices will support the constraints you supply, so they can either fail or fallback to safe values.
