### ISSUE TITLE
Portrait mode

### ISSUE THREAD

**Issue by iamchathu** [mozmorris/react-webcam#210]
Any way capture in portrait mode rather than landscape mode?

**Comment by allomorphy** [comment]
Hi iamchatu,

Portrait works for us out of the box. What issue do you have?

Best wishes,
Eric

**Comment by iamchathu** [comment]
I used sample code in the readme

```js
const videoConstraints = {
  width: 720,
  height: 1280,
  facingMode: "environment"
};

const WebcamCapture = () => {
  const webcamRef = React.useRef(null);

  const capture = React.useCallback(
    () => {
      const imageSrc = webcamRef.current.getScreenshot();
    },
    [webcamRef]
  );

  return (
    <>
      <Webcam
        audio={false}
        height={1280}
        ref={webcamRef}
        screenshotFormat="image/jpeg"
        width={720}
        videoConstraints={videoConstraints}
      />
      <button onClick={capture}>Capture photo</button>
    </>
  );
};
```

Also this didn't worked in Chrome Android and Chrome and Safari in iOS. Worked on Chrome in macOS

**Comment by allomorphy** [comment]
Obvious 🤦‍♂ things first, you have enabled autorotate on your device?

We have auto rotate functionality with code similar to ☝️.
FWIW, we either do not specify the width and height or we leave these settings out of the videoConstraints and we have them identical (like both 1920 in our case) in the <Webcam/> settings.

I hope that you get it working for you.

**Comment by mozmorris** [comment]
@iamchathu please see #213 for further details.

**Comment by theomartiz** [comment]
Hi everybody,

I am currently trying to use the Webcam component in my application. For portrait mode, works well on desktop but not on mobile with the aspectRatio constraints. It works with the width and height props but it's less convenient. I see on the MDN that aspectRatio is compatible with mobile devices. Why do we have this issue ?

Thanks, Théo

**Comment by orbachar** [comment]
@theomartiz having the same issue, did you manage to fix it?

**Comment by jonathanmv** [comment]
Same here. Not even fixed `width` and `height` work for me on mobile browsers. Did @orbachar  or @theomartiz solve this?

**Comment by haZya** [comment]
`object-fit: cover;` might help.
