### ISSUE TITLE
aspect ratio

### ISSUE THREAD

**Issue by imcodingideas** [mozmorris/react-webcam#213]
Hello,

Thanks for this component. Do you have anything to let us change the video aspect ratio?

**Comment by mozmorris** [comment]
@imcodingideas how about this example: https://codepen.io/mozmorris/pen/GRpEQwK?editors=0010

**Comment by imcodingideas** [comment]
I like your style. Thank you. I didn't see aspectRatio on the MediaStreamConstraints object.  https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints/video

**Comment by imcodingideas** [comment]
I do see: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints

Maybe we can link this in the documentation? If I make a PR with this would that be fine?

**Comment by mozmorris** [comment]
That would be great. There’s a facingMode example to use as a guide. Please link to the above demo.
