### ISSUE TITLE
Not Working on Chrome (iPhones)

### ISSUE THREAD

**Issue by vartikaongraph** [mozmorris/react-webcam#216]
I am using this package in my react app. It is working correctly on Android but not on iPhone not even asking for permissions

**Comment by mozmorris** [comment]
@vartikaongraph can you check this demo works? https://codepen.io/mozmorris/pen/JLZdoP

**Comment by allomorphy** [comment]
Hi

We had this exact issue at the start of our development and discovered 
that it was a CSS issue with our overlay. The same code worked perfectly 
in Android.

I hope this helps.

Best wishes,
Eric

vartikaongraph wrote on Wed-20-May 20  9:48AM

**Comment by vartikaongraph** [comment]
@allomorphy How did you find that which css is conflicting

**Comment by vartikaongraph** [comment]
I checked with multiple iPhone, it is working in Safari but not in Chrome

**Comment by mozmorris** [comment]
@vartikaongraph unfortunately Chrome uses a WebView on iOS. getUserMedia is currently not supported. See #95 for more details.

**Comment by vartikaongraph** [comment]
Is there any alternative?

**Comment by mozmorris** [comment]
There is not unfortunately.

**Comment by vartikaongraph** [comment]
One last query, Is there any other react packages which supports Chrome also. I really need this to work with every browser in every device.
Thanks for your response

**Comment by allomorphy** [comment]
@Vartikaongraph,

Re support on iOS, I think that this first answer still applies:
https://stackoverflow.com/questions/29160819/how-to-use-getusermedia-in-chrome-for-ios

I.e. it is a forced restriction of Apple on their ios Platform (with no 
workaround possible).  If you are on iOS, then you have your users need 
to use Safari.

Re how we found out, our chief dev worked it out another one managed to 
simplify the css to support also Safari.

Happy to share if it will help anyone.

Best
Eric

vartikaongraph wrote on Wed-20-May 20 11:06AM

**Comment by mozmorris** [comment]
@allomorphy thanks for the extra input, much appreciated.
