### ISSUE TITLE
mimetype video/mp4

### ISSUE THREAD

**Issue by krean93** [mozmorris/react-webcam#218]
Is it by any chance possible to have mp4 as the output of the recorded video?

I'm having this error with the example: https://codepen.io/mozmorris/pen/yLYKzyp?editors=0011
`Uncaught NotSupportedError: Failed to construct 'MediaRecorder': Failed to initialize native MediaRecorder the type provided (video/mp4) is not supported.`

Thanks!

**Comment by mozmorris** [comment]
I don't believe browsers yet have support for recording in MP4. 

There's a `MediaRecorder.isTypeSupported()` method which you could use to check. Your best bet would be to convert on the server side.
