### ISSUE TITLE
Image Rotation in Mobile

### ISSUE THREAD

**Issue by vartikaongraph** [mozmorris/react-webcam#219]
When I tried to click picture from mobile camera it is being rotated. Does webcam provide any attribute for fix orientation?

**Comment by mozmorris** [comment]
@vartikaongraph can you provide an example? 

And give this demo a try: https://codepen.io/mozmorris/pen/gOOoqpw?editors=0011

**Comment by vartikaongraph** [comment]
@mozmorris  I tried and it is working fine in my laptop but not working correctly for mobile phone. Image is rotating every time

**Comment by mozmorris** [comment]
What mobile device are you using?

**Comment by vartikaongraph** [comment]
Android mobile and iPhone both.

**Comment by mozmorris** [comment]
What version of the iPhone @vartikaongraph? I have an iPhone 8 and XS here, both running latest iOS `13.4.1` - the demo I sent captures the image with the correct orientation.

Can you run through the steps? When you say "click" picture, what process are you following?

If you have some example code that would also be very helpful.

**Comment by vartikaongraph** [comment]
`import React, {useState} from 'react';
import Webcam from "react-webcam";
import { Button, Row, Col  } from 'reactstrap'
import './styles.scss'
import  FA  from 'react-fontawesome'
import {isMobile} from 'react-device-detect';

const WebcamCapture = ({capturedPhoto}) => {
    const webcamRef = React.useRef(null);
    const [imageSrc, setImageSrc] = useState(null);
    const [status, setStatus] = useState(null);
    const capture = React.useCallback(
        () => {
        const imageSrc = webcamRef.current.getScreenshot();
        // capturedPhoto(imageSrc)
        setImageSrc(imageSrc)
        setStatus('captured')
        },
        [webcamRef]
    );

    const videoConstraints = {
        facingMode: isMobile ?  { exact: "environment" } : "user",
    };

    const handleUseImage = () => {
        setStatus(null)
        capturedPhoto(imageSrc)
    }
    return (
        <Row className=' no-margin'>
            <Col xs={12} className='webCamDiv'>
                {
                    status == 'captured' ? <img src={imageSrc} /> :
                    <Webcam
                    audio={false}
                    // height={720}
                    ref={webcamRef}
                    screenshotFormat="image/jpeg"
                    // width={1280}
                    videoConstraints={videoConstraints}
                    />
                }

            </Col>
            <Col md={{size:6, offset:3}} className="text-center">
                {
                    status == 'captured' ?
                    <React.Fragment>
                        <Button color='primary' size='sm' onClick={()=> handleUseImage() } block> USE</Button>
                        <Button color='secondary'  size='sm' onClick={()=> setStatus(null) } block>TAKE AGAIN</Button>
                    </React.Fragment>
                    :
                    <React.Fragment>
                        <Button color='primary' size='sm'onClick={capture}>
                            <FA  size='lg' className='cameraBtn' name='camera' />
                        </Button>
                    </React.Fragment>

                }

            </Col>

        </Row>

        )
    }

export default WebcamCapture
`

`  handleImageOnChange(event){
    let updated_item = {...this.state.new_item}
    updated_item.image_placeholder = URL.createObjectURL(event.target.files[0])
    updated_item.file = event.target.files[0]
    this.setState({
      new_item : updated_item
    })
  }


  /*
  helper function to get the image file ready for upload.
  */
  createImage(file) {
    let reader = new FileReader();
    let updated_item = {...this.state.new_item}
    reader.onload = (e) => {
      updated_item.image = e.target.result
      this.setState({
        new_item : updated_item
      })
      this.handlePublishItem()
    };
    reader.readAsDataURL(file);
  }`

This is the code that I am using.

**Comment by mozmorris** [comment]
@vartikaongraph I've taken your example and re-created it on CodePen. Tested on MacOS, iOS (iPhone 8 & XS), Windows 10 (internal and external webcam)

https://codepen.io/mozmorris/pen/jObdbpb?editors=0010

**Comment by mozmorris** [comment]
@vartikaongraph since I can see you have upload code, I'm guessing your issue might be on the server side. Please feel free to reopen this issue if you still think it's something wrong with react-webcam.

Pleas note, I'm using this library on various projects in the wild where we upload images from user's devices and this isn't something I've come across.
