### ISSUE TITLE
Webcam Video can't display  height more than 720px in Safari and Firefox

### ISSUE THREAD

**Issue by ggican** [mozmorris/react-webcam#220]
Hello 

Thank you for library

I had an issue in firefox and safari if I set height video more than 720px, react-webcam can't set height more than 720px, that is an issue in safari and firefox

here is example my videoConstraints in react webcam
 ```
<Webcam
 height={1280}
 width={720}
 ref={e => (this.webcam = e)}
 onUserMedia={this.handleUserMedia}
 videoConstraints={{
    width:720,
    height:1280,
 }}
 />
```
With these settings i can't get webcam video height with 1280px just 720px in safari and firefox
thank you very much

**Comment by mozmorris** [comment]
@ggican this will depend on the capabilities of your media device. eg. it may well only support up to 720 (I have the same issue on my desktop)

If you wish you fill a larger space with the video, I would suggest using CSS.

**Comment by mozmorris** [comment]
Here's an example. Note that the video constraints have smaller dimensions than the styling being applied to the video element.

```jsx
<Webcam
  height={1280}
  width={720}
  ref={(e) => (this.webcam = e)}
  onUserMedia={this.handleUserMedia}
  videoConstraints={{
    width: 360,
    height: 640
  }}
/>
```
