### ISSUE TITLE
Can I use the webcam without actually displaying a video feed on screen?

### ISSUE THREAD

**Issue by donovan-PNW** [mozmorris/react-webcam#221]
I'm trying to hide the video canvas while only displaying screenshots to the user. I've tried the usual CSS tricks: if I try to display it off screen or hide it completely, the component itself seems to work but the webcam gets no data (or a black screen). Am I missing a setting/method that can handle this?

Thanks!

**Comment by mozmorris** [comment]
@donovan-PNW you mean like this: https://codepen.io/mozmorris/pen/VwvgzVZ?editors=0010

**Comment by donovan-PNW** [comment]
@mozmorris Exactly like that! Thanks you're a lifesaver!

**Comment by mozmorris** [comment]
No problem 👍

**Comment by betaflag** [comment]
Not sure if chrome changed something recently but this gives me a black image and this solution no longer works.

**Comment by mozmorris** [comment]
@betaflag have updated the demo: https://codepen.io/mozmorris/pen/VwvgzVZ?editors=0010

**Comment by mozmorris** [comment]
Try the updated demo again, hopefully sorted. https://codepen.io/mozmorris/pen/VwvgzVZ?editors=0010

**Comment by shzcuber** [comment]
it stopped working
