### ISSUE TITLE
After capture, camera is not closed

### ISSUE THREAD

**Issue by Dhavalptel** [mozmorris/react-webcam#222]
After the image is captured and the component is changed, the camera is still opened. It does not get closed.

**Comment by mozmorris** [comment]
@Dhavalptel do you have any further details e.g browser, device? Maybe an example?

Here's a CodePen: https://codepen.io/mozmorris/pen/pojYEPR?editors=0010

Tested on MacOS, iOS (iPhone 8 & XS)

**Comment by Dhavalptel** [comment]
I've checked that. But still it is not working

**Comment by Dhavalptel** [comment]
Here is the code, please take a look and let me know...
```
{imageData ? (
                <img
                  height={300}
                  width={400}
                  src={URL.createObjectURL(imageData)}
                  alt=""
                />
              ) : webcamExists && !imageData ? (
                <Webcam
                  audio={false}
                  //   height={350}
                  ref={webcam}
                  screenshotFormat="image/png"
                  width={400}
                  videoConstraints={videoConstraints}
                  capture={() => setImageData(webcam.current.getScreenshot())}
                />
              ) : (
                <img src="/images/verification.svg" alt="" />
              )}
``` 

In this, when user captures the photo, `imageData` will have the data ( I've tested and it is working for sure ).

I also checked that after the image is captured does the webcam code is rendered or not. That code is also not rendering...

But still the camera does not close. Also when I go to some other route, the camera does not close.

**Comment by mozmorris** [comment]
I've recreated your example on CodePen here: https://codepen.io/mozmorris/pen/xxweLMz?editors=0010

I've added the missing variable initialisations for `webcamExists` and `videoConstraints` so you may wish to add your own logic to how these are created.

Currently, it doesn't do anything since `Webcam` doesn't take a `capture` prop. Could you fork it and amend so that it's the same as your own application?

**Comment by mozmorris** [comment]
Oh, and what device/browser are you using?

**Comment by Dhavalptel** [comment]
I'm using mac and running the site in chrome

**Comment by mozmorris** [comment]
What's the Chrome version?

**Comment by Dhavalptel** [comment]
Hey Morris, I've updated the codepen.

The chrome version is :- 81.0.4044.138

**Comment by mozmorris** [comment]
Great, unfortunately the example doesn't work for me - I get a blank screen. There's an error on the page, check the console.

![Screen Shot 2020-05-26 at 11 06 45](https://user-images.githubusercontent.com/156303/82888284-0abbec80-9f41-11ea-87ec-0be8feaa20f5.png)

Additionally, you're creating your own stream via getUserMedia. If you don't kill this stream on navigation/unmount, it will still exist.

Note, react-webcam handles this for you - there's no need to call getUserMedia yourself.

**Comment by Dhavalptel** [comment]
I agree. But when I'm not creating my own stream, the camera is not getting on.

**Comment by mozmorris** [comment]
That sounds like a different issue to this one. I'm closing this since you're creating a stream outside of react-webcam and I'm confident that is why the camera remains on,

**Comment by Dhavalptel** [comment]
But when not creating the stream, the camera is still on

**Comment by mozmorris** [comment]
Please create an example without creating another stream.
