### ISSUE TITLE
Webcam always on

### ISSUE THREAD

**Issue by ionalexandrusecara** [mozmorris/react-webcam#229]
- [x] Is your app running over HTTPS?
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?

Hey everyone!

I've been using react-webcam for a while now, and I've just recently noticed a bug. I use react-router and when I change the page/route but the camera is still loading/booting up, the camera will continue loading and stay on until the website is closed. The camera stays on, no matter where I navigate. This is an issue as people can think I'm spying on them, so I'm wondering if anyone found a way to release the camera or stop it from loading when the user leaves the page.

**Comment by ClubSpeedJustinG** [comment]
I am running into the same issue.

**Comment by acornwall** [comment]
Sorry, I ended up making a duplicate issue with a fix for this. See #232 for how to resolve this. There's a race-condition where you're unmounting before `#handleUserMedia` gets called. The fix is only a few lines of code.

**Comment by mozmorris** [comment]
@acornwall closing in favour of #232
