### ISSUE TITLE
onUserMediaError not Running correctly

### ISSUE THREAD

**Issue by akshayvenugopal07** [mozmorris/react-webcam#230]
## Please follow the general troubleshooting steps first:

- [YES ] Is your app running over HTTPS?
- [ YES] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?

### Bug reports:

Hey @mozmorris 

Please help I know that react-webcam has issues rendering in webviews but if the camera fails the onUserMediaError is not being run in these webviews is there any way I can detect if the camera has error, its OK if the permission is denied or if there is an issue I just need to be notified somehow. Please help in any way you can its really critical for the application.

[https://codepen.io/akshayvenugopal007/pen/QWyWLOX](https://codepen.io/akshayvenugopal007/pen/QWyWLOX)

**How to reproduce**
Put the link in a post it in social media (I sent it in Instagram chat and opened the link) which opened in a webview but the onMediaError was not thrown

**I can share my camera page code as needed please help let me know if you need any other details Project created from create react app and it uses react hooks and the application is a PWA**

"dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "app-registry": "^1.0.1",
    "axios": "^0.19.2",
    "babel-core": "7.0.0-bridge.0",
    "babel-plugin-react-intl": "^6.0.1",
    "crypto-js": "^4.0.0",
    "gulp": "3.9.1",
    "gulp-commonjs-tasks": "^1.2.0",
    "gulp-util": "^3.0.8",
    "history": "^4.10.1",
    "libphonenumber-js": "^1.7.52",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-gtm-module": "^2.0.8",
    "react-intl": "2.8.0",
    "react-intl-redux": "2.1.0",
    "react-intl-translations-manager": "^5.0.3",
    "react-notifications": "^1.6.0",
    "react-phone-input-2": "2.13.5",
    "react-redux": "^7.2.0",
    "react-responsive-carousel": "^3.2.7",
    "react-router-dom": "^5.2.0",
    "react-router-redux": "^4.0.8",
    "react-scripts": "3.4.1",
    "react-webcam": "^5.1.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "seamless-immutable": "^7.1.4"
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-transform-runtime": "^7.6.2",
    "@babel/preset-env": "^7.6.3",
    "@babel/preset-react": "^7.6.3",
    "@storybook/addon-actions": "^5.3.18",
    "@storybook/addon-links": "^5.3.18",
    "@storybook/addons": "^5.3.18",
    "@storybook/preset-create-react-app": "^2.1.2",
    "@storybook/react": "^5.3.19",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.9.0",
    "babel-loader": "^8.0.6",
    "config": "^3.2.3",
    "cross-env": "^6.0.3",
    "css-loader": "^3.2.0",
    "del-cli": "^3.0.0",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.15.1",
    "enzyme-to-json": "^3.4.3",
    "eslint": "^6.5.1",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-html-reporter": "^0.7.4",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.16.0",
    "file-loader": "^4.2.0",
    "identity-obj-proxy": "^3.0.0",
    "import-glob": "^1.5.0",
    "istanbul": "^0.4.5",
    "jest": "^24.9.0",
    "jest-cli": "^24.9.0",
    "jest-junit": "^8.0.0",
    "mini-css-extract-plugin": "^0.8.0",
    "node-sass": "^4.14.1",
    "npm-run-all": "^4.1.5",
    "pre-commit": "^1.2.2",
    "sass-loader": "^8.0.0",
    "style-loader": "^1.0.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 9009 -s public",
    "build-storybook": "build-storybook -s public",
    "test": "cross-env jest -i",
    "reports": "run-p eslint-report coverage-summary",
    "eslint": "cross-env eslint 'src/**/*.js' 'src/**/*.jsx'",
    "eslint-json-summary": "npm run eslint -- -f json > ./reports/eslint.json",
    "eslint-report": "cross-env eslint 'src/**/*.js' 'src/**/*.jsx' -f node_modules/eslint-html-reporter/reporter.js -o reports/eslint.html",
    "coverage": "cross-env jest -i --coverage",
    "coverage-summary": "cross-env istanbul report --root ./ --include reports/coverage/coverage-final.json --dir ./reports json-summary",
    "prep-translations": "cross-env NODE_CONFIG_DIR=./config/env NODE_ENV=development gulp prepTranslations",
    "check-translations": "cross-env NODE_CONFIG_DIR=./config/env NODE_ENV=development gulp checkTranslations"
  },

![Screenshot_20200805-165401_Instagram](https://user-images.githubusercontent.com/44598082/89407422-69b99100-d73c-11ea-9c67-352bb14804ae.jpg)

This is the sample of the error I faced no alert was triggered

**Comment by akshayvenugopal07** [comment]
![Screenshot_20200805-162933_Instagram](https://user-images.githubusercontent.com/44598082/89407275-1fd0ab00-d73c-11ea-8ee8-19cee3ce3b7a.jpg)

This image depicts the error page hope its helpfull

**Comment by akshayvenugopal07** [comment]
Any updates @mozmorris

**Comment by mozmorris** [comment]
@akshayvenugopal07 thanks for you patience @akshayvenugopal07 but I've not had a chance to look at this. Perhaps you could try debugging it yourself and seeing why the error handler isn't called?

**Comment by mozmorris** [comment]
Closing in favour of #211
