### ISSUE TITLE
Stream doesn't always stop on component unmount.

### ISSUE THREAD

**Issue by acornwall** [mozmorris/react-webcam#232]
## Please follow the general troubleshooting steps first:

- [x] Is your app running over HTTPS?
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device? Yes. The demo worked fine, but I was unable to reproduce this bug even after adding a toggle for the webcam on the demo.

### Bug reports:

I tried to make a repro of this issue, but had trouble reproducing it in a non-production environment. In my production environment, the first time `<Webcam />` is rendered it gets unmounted very fast (before `#handleUserMedia` gets called in the `navigator.mediaDevices#getUserMedia` callback but after #doRequestUserMedia gets called). This means `#componentWillUnmount` gets called, nothing gets cleaned up, and then `this.stream` is set in `#handleUserMedia` (which never gets cleaned up because the component is in the middle of unmounting / has already unmounted).

The result is you end up in a state where the stream remains open and your webcam remains on even after `<Webcam />` has unmounted.

A simple fix is to set a variable in `#componentWillUnmount`, and then immediately stop the stream's video and audio tracks in `#handleUserMedia` and return if the variable is set.

e.g.
```typescript
private isUnmounting = false;

componentWillUnmount() {
    this.isUnmounting= true;
    this.stopAndCleanup();
  }

// Pulled out of #stopAndCleanup
private stopStream() {
    const {stream} = this;
    if (stream) {
      stream.getVideoTracks().map(track => track.stop());
      stream.getAudioTracks().map(track => track.stop());
    }
  }

private handleUserMedia(stream: MediaStream) {
    const {props} = this;
    this.stream = stream;

    // Fix for when #handleUserMedia is called after #componentWillUnmount.
    if (this.isUnmounting) {
      this.stopStream();
      return;
    }

   // ...
}
```

**Comment by mozmorris** [comment]
@acornwall would be great if you could create a PR for this :-)

**Comment by ClubSpeedJustinG** [comment]
I attempted the solution that was provided by @acornwall, but I didn't have any luck. Perhaps I can create a small sample app that can reproduce the issue to continue to troubleshoot.

**Comment by keithpickering** [comment]
@acornwall Thank you for looking into this issue! I think we're experiencing it as well. Would you mind creating a pull request so we don't have to create/maintain our own fork?

**Comment by acornwall** [comment]
Hi, Keith. I don't have the spare time to work on this right now. Please feel free to make a pull request and take credit for a fix.

**Comment by paweldomas** [comment]
Hi there!
Here's a PR which fixes this issue for us (pretty much what described above):
https://github.com/mozmorris/react-webcam/pull/238

**Comment by mozmorris** [comment]
@paweldomas if you can confirm the `5.2.1` published version fixes this, we can close. And thank you again.

**Comment by mozmorris** [comment]
@acornwall if you get the time could you also test the latest version. Thank you :-)

**Comment by paweldomas** [comment]
@mozmorris `5.2.1` fixes the problem for me
