### ISSUE TITLE
Not working on IOS chrome. 

### ISSUE THREAD

**Issue by Avi98** [mozmorris/react-webcam#234]
## Please follow the general troubleshooting steps first:

- [x] Is your app running over HTTPS?
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?

### Bug reports:

Tried to run the demo (https://codepen.io/mozmorris/pen/JLZdoP) on IOS chrome. Not working. But it's working on  safari

**Comment by mozmorris** [comment]
@Avi98 unfortunately Chrome uses a WebView on iOS. getUserMedia is currently not supported. See #95 for more details.

**Comment by Avi98** [comment]
@mozmorris I found a workaround it by using. I have added a check if not 

```navigator.mediaDevices.getUserMedia !== undefined ``` then render this

```html
<input
type="file"
          accept="image/*"
          ref={ref => {
            this.video = ref;
          }}
          capture="camera"
/>
```
