### ISSUE TITLE
Doesn't work in Facebook Messenger in-app browser (Android and iOS)

### ISSUE THREAD

**Issue by keithpickering** [mozmorris/react-webcam#235]
## Please follow the general troubleshooting steps first:

- [X] Is your app running over HTTPS?
- [X] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?

### Bug reports:

React-webcam doesn't prompt the user to allow camera/mic access when viewed with Facebook's in-app browser.

Since I'm guessing this is a permission issue with webviews or something, is there a good workaround? Right now we're just detecting the faulty browser and displaying a modal which lets the user know they need to open the link in a real browser instead. But there's no way we've found to redirect it programmatically, which is a huge bummer.

**Comment by mozmorris** [comment]
@keithpickering unfortunately this uses a WebView. getUserMedia is currently not supported. See #95 for more details.
