### ISSUE TITLE
Calling getScreenshot() immediately on stream can return null

### ISSUE THREAD

**Issue by innovative-piggy** [mozmorris/react-webcam#236]
## Please follow the general troubleshooting steps first:

- [ ] Is your app running over HTTPS? Yes, it does
- [ ] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device? Yes, I did.

### Bug reports:

I've deployed a basic webcam project on https://camctr.web.cam
It gets screenshot on camera start (try every second until getting valid screenshot image) and show the screenshot instead of camera stream after a few seconds.
Android works well with this.
Problem is iOS browsers. It shows camera stream, but doesn't capture the camera. getScreenshot() is completely not working.

I tried like below
webcamRef.current.getScreenshot()

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by mozmorris** [comment]
@innovative-piggy unfortunately your link doesn't work for me so I can't test.

However, I have a capture example here: https://codepen.io/mozmorris/pen/gOOoqpw (tested and working on the latest iOS iPhone 8 and XS)

Let me know how you get on.

**Comment by innovative-piggy** [comment]
Hi @mozmorris thanks for your info.
I've called the getScreenshot() onUserMedia, but it returned null.
So I've set up interval until it gets actual screen image dataUrl.
I think that's the problem on iPhone?

What I want to ask now is, how can I get the event when the webcam component starts streaming the actual camera video?
As I mentioned, onUserMedia didn't work. 
Many thanks.

**Comment by innovative-piggy** [comment]
I mean how can I capture the screenshot on camera start?

**Comment by mozmorris** [comment]
Okay interesting, I can see where is the issue is. We call `onUserMedia` immediately upon getting the stream but at this point the stream hasn't been rendered to the page. Therefore calling `getScreenshot()` will return `null`.

Can you try this example: https://codepen.io/mozmorris/pen/dyMrMMw?editors=0011

**Comment by innovative-piggy** [comment]
Thanks, @mozmorris 
I've successfully got screenshot by calling it onPlay={handleScreenshot()}. It works!
By the way, does it support all browsers on iOS? or only Safari?

**Comment by mozmorris** [comment]
Only Safari is supported as getUserMedia is not supported inside Webviews (which is what Chrome uses on iOS)

**Comment by innovative-piggy** [comment]
Thank you for your assistance @mozmorris 
My issue has been solved!
