### ISSUE TITLE
How can I save the image in Local Folder as well as Database such as MongoDB

### ISSUE THREAD

**Issue by Rama144** [mozmorris/react-webcam#239]
I achieved Capturing screenshot and displaying it in the HTML
But can someone help me how to save it into Local Folder as well as to the database . 

I had provided my code below 

````

import React, { Component } from "react";
import Webcam from "react-webcam";

const Camera = () => {
    const webcamRef = React.useRef(null);
    const [imgSrc, setImgSrc] = React.useState(null);
  
    const capture = React.useCallback(() => {
      const imageSrc = webcamRef.current.getScreenshot();
      setImgSrc(imageSrc);
    }, [webcamRef, setImgSrc]);
  
    return (
      <>
        <Webcam
          audio={false}
          ref={webcamRef}
          screenshotFormat="image/jpeg"
        />
        <button onClick={capture}>Capture photo</button>
        {imgSrc && (
          <img
          src={imgSrc}
        />
        )}
      </>
    );
  };
  

export default Camera

````

I know this is a small issue , But I couldn't find it else where . 
Any help would be much appreciated . Thanks

**Comment by mozmorris** [comment]
@Rama144 you need to upload the base64 image string to your server. I would suggest using the `fetch` api to do this.

Perhaps search/ask on Stackoverflow to see if anyone can help you. Best of luck.

Here's an example I created to capture video which can be downloaded. You could adapt this to work with the image. https://codepen.io/mozmorris/pen/yLYKzyp?editors=0011
