### ISSUE TITLE
Do you have any plan for mirror options?

### ISSUE THREAD

**Issue by smronju** [mozmorris/react-webcam#24]
Do you have any plan for mirror options? Cause it shows flip image in browser and saves the same.

**Comment by cezary** [comment]
I'm reluctant to add a mirror prop to react-webcam. It seems like you can accomplish mirrored view by just setting the style attribute. In that case, it's similar to the filter examples in the demo. Would being able to pass a style prop be sufficient instead? Something like this

```js
<Webcam
  style={{
  }}
/>
```

**Comment by smronju** [comment]
That doesn't solve the problem. When you save the image it flips in preview.

**Comment by makis-spy** [comment]
Has anyone made any progress on this? Would be nice to not have to process say a snap shot image after the fact.

Thanks!

**Comment by jasan-s** [comment]
@smronju which PR ? has it been merged in to master? i dont see an option to mirror in docs
