### ISSUE TITLE
Android - Flickering Camera on Samsung S9

### ISSUE THREAD

**Issue by paulVulog** [mozmorris/react-webcam#240]
Hi, 

I am facing a strange issue that I can only reproduce on my Samsung Galaxy S9 (Emulators and most of other devices are fine). 

I can reproduce using the demo URL : https://codepen.io/mozmorris/pen/JLZdoP
Here is the strange result I get: 
The very first time I launch my app ( or if I start from a fresh App Data cleaning ), everything works fine on my device.
-> The webview request the permission
-> The permissions (audio / video) are granted
-> The camera works fine

![image](https://user-images.githubusercontent.com/24452432/95586951-b32aa300-0a41-11eb-8937-1a2a735782cf.png)

If I close my app ( the app is just closed, not killed ), then everything is fine when I go back in the app.
BUT, as soon as the app is killed ( ex : swiped from the Recent App list ) 
The video camera stream is Flickering and display weird colors (blue and red are kind of inverted) : 

![image](https://user-images.githubusercontent.com/24452432/95588147-562fec80-0a43-11eb-9e83-95154b084684.png)

From that point, until the app data are cleaned up, their is no possibility to get back a good camera preview.

Did you already get this kind of issue ?
Perhaps it's linked to this one : https://github.com/mozmorris/react-webcam/issues/211

Finally, something weird is the fact that if I try the same demo URL on the Chrome app, I am not able to reproduce. 
It's probably it's probably deeply linked to the WebView Android component. 
I guess it's related to a missing configuration on my WebView implementation. But I have tried A lots of different configuration without any success. 

Thanks.

**Comment by mozmorris** [comment]
@paulVulog firstly, thanks for the detailed report.

This is quite interesting since in the issue you linked to (#211) others weren't even able to get the component to work in a WebView. Would you mind posting your config over on that issue? That will probably help others having issues. I'd also be interested to see it as well.

On your own issue, have you tested any other getUserMedia implementation to see if you get the same result? eg https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Comment by paulVulog** [comment]
Hi @mozmorris .

I can reproduce the exact same issue with a brand new app only to test this use case. 
Here is the minimal code required to have your URL working - except for my Samsung S9 : ( https://codepen.io/mozmorris/pen/JLZdoP ) 

**Android Manifest Permission:** 


```
        <uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.RECORD_AUDIO" />
	<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

```

**Android WebView Component :** 


```
	<WebView
		android:id="@+id/test_webview"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		/>
```


**Android Activity (full code) :** 


```
package com.we.testwebview;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.webkit.PermissionRequest;
import android.webkit.WebChromeClient;
import android.webkit.WebSettings;
import android.webkit.WebView;

public class MainActivity extends AppCompatActivity {

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		//retrieve the view
		WebView myWebView = (WebView) findViewById(R.id.test_webview);

		//setup the minimal settings
		//https://developer.android.com/guide/webapps/webview
		final WebSettings settings = myWebView.getSettings();
		settings.setJavaScriptEnabled(true);
		myWebView.setWebChromeClient(new WebChromeClient(){
			@Override
			public void onPermissionRequest(PermissionRequest request) {
				request.grant(new String[]{PermissionRequest.RESOURCE_VIDEO_CAPTURE, PermissionRequest.RESOURCE_AUDIO_CAPTURE});
			}
		});

		//mozmorris Test Url
		myWebView.loadUrl("https://codepen.io/mozmorris/pen/JLZdoP");
		//other
		//myWebView.loadUrl("https://webrtc.github.io/samples/src/content/getusermedia/gum/");

	}
	
}

```

------

Reminder : 
This code works fine on my Nexus 5X. ( you need to force the Camera + Audio Permissions in the app configuration before launching this app ) 
But, on my Samsung S9, Only the first launch is fine. As soon as you kill the app, the following app launch will result in a Weird / Blueish / Flickering camera behavior.

-------

In addition, I am not able to make this URL  ( https://webrtc.github.io/samples/src/content/getusermedia/gum/ ) working with this code ( even with some updates) . Everything looks fine, but the picture is never display on all my devices : 

![image](https://user-images.githubusercontent.com/24452432/95996743-52310f80-0e33-11eb-88e8-90553339a6f7.png)


------

I have done some additional test by replacing the webview by a ChromeTab : 
https://developer.chrome.com/multidevice/android/customtabs

The code is the following : 

```
				// Use a CustomTabsIntent.Builder to configure CustomTabsIntent.
				CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
				CustomTabsIntent customTabsIntent = builder.build();
				// and launch the desired Url
				customTabsIntent.launchUrl(MyActivity.this , Uri.parse(URL_TO_LAUNCH));
```

The chrome Tab works fine on My Samsung S9 and the nexus 5X with both URLs (https://codepen.io/ and  https://webrtc.github.io/) .
So the issue here only relates to WebView on Android.... on some specific devices.


------ 

Let me know if you have any idea on this.

**Comment by mozmorris** [comment]
Closing in favour of #211
