### ISSUE TITLE
Unable play recorded videos using media player

### ISSUE THREAD

**Issue by amanadi007** [mozmorris/react-webcam#241]
I'm trying to capture the video using react-webcam and preview the captured video on a video player. I followed this [example](https://codepen.io/mozmorris/pen/yLYKzyp?editors=0010) where the video can be downloaded, however when extending the solution to play the video, i'm getting an error ``GET blob:https://cdpn.io/fd3c6cb3-469e-4ad3-9b9c-3aed6407e4d3 net::ERR_FILE_NOT_FOUND``, Related [codepen link](https://codepen.io/amanadi007/pen/BazNbzw).

Am i doing something wrong here? I know this is a small issue , But I couldn't find it else where. Any help would be much appreciated. Thanks

**Comment by mozmorris** [comment]
@amanadi007 you need to remove the line `window.URL.revokeObjectURL(url);` as this will delete the reference to the object.

**Comment by mozmorris** [comment]
...and thank you for providing a CodePen 👍

**Comment by amanadi007** [comment]
Cool. Thanks for the help 😄👍

**Comment by amanadi007** [comment]
@mozmorris, is there any way to get the recorded video blob when mediaRecorder stops, i tried this by adding event listener on stop property but the recordedChunks is still empty? Related [codepen link](https://codepen.io/amanadi007/pen/BazNbzw), is there anything i'm doing wrong here?
