### ISSUE TITLE
Work in codepen, work in laptop device, but not in mobile device

### ISSUE THREAD

**Issue by hiep294** [mozmorris/react-webcam#242]
- [x] Is your app running over HTTPS?
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?

### Bug reports:
Lib has worked correctly in browser of laptop or codepen, but in mobile device, it showed nothing
https://github.com/hiep294/react-webcam-demo
Thank you!.

**Comment by mozmorris** [comment]
@hiep294 thanks for this report.

1. Could you provide a link to where your application is deployed?

2. What mobile device are you testing on?

**Comment by hiep294** [comment]
> @hiep294 thanks for this report.
> 
> 1. Could you provide a link to where your application is deployed?
> 2. What mobile device are you testing on?

may be need to set up https for website, thank you
