### ISSUE TITLE
Back Camera is not working

### ISSUE THREAD

**Issue by nikhil-tayal** [mozmorris/react-webcam#243]
```
class WebcamCapture extends React.Component {
  render() {
    const videoConstraints = {
      facingMode: { exact: "environment" }
    };

    return <Webcam videoConstraints={videoConstraints} />;
  }
}
```

This code not opening the back camera.

**Comment by mozmorris** [comment]
@nikhil-tayal have you tried removing the `exact`? eg `facingMode: 'environment'`

**Comment by nikhil-tayal** [comment]
Yes, I tried but not working.

**Comment by mozmorris** [comment]
@nikhil-tayal could you try taking a look at this example: https://codepen.io/mozmorris/pen/KKwdOPO

Are both your devices listed?
