### ISSUE TITLE
How can I set portrait mode?

### ISSUE THREAD

**Issue by dickyindra** [mozmorris/react-webcam#246]
## Please follow the general troubleshooting steps first:

- [x] Is your app running over HTTPS? (please provide the URL if possible)
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [x] Checked the latest "Can I use" compatbility table? (https://caniuse.com/stream)

### Bug reports:

My code: https://codesandbox.io/s/sleepy-lewin-2sle5

I tried it on my phone and the result is landscape mode,
but if I try on my laptop it is portrait mode.

Why is it different?

Test on Phone: (Chrome Browser 86.0.4240.185 - Android 10)
![photo_2020-11-11_16-23-40](https://user-images.githubusercontent.com/13186704/98793369-6835ee00-243a-11eb-8641-5459e49c2b3f.jpg)

Test on Laptop: (Chrome Browser 86.0.4240.183 - Mac OS Catalina 10.15.7)
<img width="1064" alt="Screen Shot 2020-11-11 at 16 32 16" src="https://user-images.githubusercontent.com/13186704/98794417-9c5dde80-243b-11eb-978f-f2061acd1a60.png">

Version:
react-webcam: 5.2.1
react: 17.0.0

**Comment by AlessandroGrassi1998** [comment]
I have the same issue, have you found a solution yet?

**Comment by NobbsNobby** [comment]
I hope my code helps you

```
function detectMob() {
  const toMatch = [
    /Android/i,
    /webOS/i,
    /iPhone/i,
    /iPad/i,
    /iPod/i,
    /BlackBerry/i,
    /Windows Phone/i,
  ];

  return toMatch.some((toMatchItem) => toMatchItem.test(navigator.userAgent));
}

...

const getVideoConstraints = () => {
    return mobileVersion
      ? {
          width: 720,
          height: 539,
        }
      : {
          width: 539,
          height: 720,
        };
  };

...

<StyledWebcam
                audio={false}
                forceScreenshotSourceSize={true}
                ref={webcamRef}
                screenshotFormat="image/jpeg"
                videoConstraints={{
                  ...getVideoConstraints(),
                  facingMode: 'environment',
                }}
                onUserMedia={() => {}}
              />

```

**Comment by dickyindra** [comment]
> I hope my code helps you
> 
> ```
> function detectMob() {
>   const toMatch = [
>     /Android/i,
>     /webOS/i,
>     /iPhone/i,
>     /iPad/i,
>     /iPod/i,
>     /BlackBerry/i,
>     /Windows Phone/i,
>   ];
> 
>   return toMatch.some((toMatchItem) => toMatchItem.test(navigator.userAgent));
> }
> 
> ...
> 
> const getVideoConstraints = () => {
>     return mobileVersion
>       ? {
>           width: 720,
>           height: 539,
>         }
>       : {
>           width: 539,
>           height: 720,
>         };
>   };
> 
> ...
> 
> <Webcam
>                 audio={false}
>                 forceScreenshotSourceSize={true}
>                 ref={webcamRef}
>                 screenshotFormat="image/jpeg"
>                 videoConstraints={{
>                   ...getVideoConstraints(),
>                   facingMode: 'environment',
>                 }}
>                 onUserMedia={() => {}}
>               />
> ```

Thank you, but does not solve the camera resolution problem.

**Comment by Jonlemos** [comment]
hi i had the same problem and solved it that way:

const videoConstraints = {
  width: 1920,
  height: 1080,
  facingMode: "environment"
}

<Webcam audio={false} className={styles.camera} videoConstraints={videoConstraints} />


style:
.camera{  
 transform: rotate(90deg);
}
