### ISSUE TITLE
How to stop camera

### ISSUE THREAD

**Issue by patilniranjan7** [mozmorris/react-webcam#247]
## Please follow the general troubleshooting steps first:

- [x] Is your app running over HTTPS? (please provide the URL if possible)
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [x] Checked the latest "Can I use" compatbility table? (https://caniuse.com/stream)

### Bug reports:

If you can provide a minimal reproducible demo (CodePen, CodeSandbox, etc) or a GitHub repository, that will greatly help us to solve your problem. Many of the issues posted are questions about react-webcam usage. We don't discourage you posting a question, it's just a lot easier to help you if we can see your code.

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by jiteshwadia** [comment]
@patilniranjan7 stopping camera works fine. But were you able to hide the video icon from address bar.

**Comment by patilniranjan7** [comment]
> @patilniranjan7 stopping camera works fine. But were you able to hide the video icon from address bar.

That mean camera is not stopped. Our problem are same bro. When camera accessed then that icon came.

**Comment by mozmorris** [comment]
Once the camera has been accessed, even if stopped the icon will remain. I've not been able to find an example where this is any different. For example, I can physically detach my camera and the icon remains.
