### ISSUE TITLE
Allow passing in an existing MediaStream

### ISSUE THREAD

**Issue by atav32** [mozmorris/react-webcam#250]
### Feature Request:
Re-rendering `<ReactWebcam/>` on Firefox will prompt the user for video permission several times. This is intentional behavior according to Mozilla, i.e. "keep the user in charge", https://github.com/mozilla/standards-positions/issues/19#issuecomment-365152565.

To avoid annoying the user and to keep the media permission user experience in-line with other browsers, I'd like to manually make a `getUserMedia()` call, hold on to that MediaStream and then pass it into `<ReactWebcam/>`.

The alternative would be to contort the app to keep `<ReactWebcam/>`'s video element from being re-rendered (maybe putting it in a portal; hiding & unhiding it; etc).

**Comment by mozmorris** [comment]
@atav32 could you provide an example of this? 

I have created a simple demo that updates a component at a 1 second interval. Tested in Firefox and I don't get asked for permission on each render. Perhaps I'm misunderstanding the problem so an example would be useful.

https://codepen.io/mozmorris/pen/KKgwZmo?editors=0010
