### ISSUE TITLE
Doesn't work on iPhone OS 13.3

### ISSUE THREAD

**Issue by nazmulshuvo03** [mozmorris/react-webcam#251]
## Please follow the general troubleshooting steps first:

- [x] Is your app running over HTTPS? (please provide the URL if possible)
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [x] Checked the latest "Can I use" compatbility table? (https://caniuse.com/stream)

### Bug reports:
Webcam works fine on Android, Windows and Ubuntu. But does not work in this device:
**iPhone XR (ios 13.3.1)**

I have tried the **Demo** and recorded the screen. Please see the following video:
`https://drive.google.com/file/d/1b-54ZRB5qbjy-NkYMhC9cXQSZf3JggWp/view?usp=sharing`

**Comment by mozmorris** [comment]
@nazmulshuvo03 thanks for this report.

Would you mind testing this WebRTC demo? https://webrtc.github.io/samples/src/content/getusermedia/gum/

Additionally, could you check the console for errors and copy them here? 👍

**Comment by nazmulshuvo03** [comment]
@mozmorris I have tried the WebRTC demo. Here is the screen record: [video](https://drive.google.com/file/d/1ksEb8m3GCQR6c7C20DoxVQJpGfa0f00X/view?usp=sharing)

I can't check the console, because it is happening on a phone.

**Comment by mozmorris** [comment]
Just realised you're using Google Chrome - unfortunately getUserMedia isn't supported inside a WebView currently (check the latest "Can I use" compatibility table)
