### ISSUE TITLE
Switching camera on iOS Safari ends in blank stream.

### ISSUE THREAD

**Issue by LKay** [mozmorris/react-webcam#252]
## Please follow the general troubleshooting steps first:

- [x] Is your app running over HTTPS? (please provide the URL if possible)
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [x] Checked the latest "Can I use" compatibility table? (https://caniuse.com/stream)

### Bug reports:

I'm trying to make a camera switcher and iOS Safari breaks when camera device is switched. On page enter the browsers asks for camera permissions and shows video stream without issues. Then if I switch camera from front to back or other way around the video stream goes blank. What I do is change `deviceId` in constraints passed to `Webcam` component. I have to refresh the page to get video stream visible again.

I tried to set up example code based on this https://codepen.io/mozmorris/pen/KKwdOPO but weird thing happen. In CodePen only one device is detected but running exactly the same code outside CodePen returns two devices, `Front Camera` and `Back Camera` separately.

You can see the videos of what's happening: https://share.getcloudapp.com/WnulNEqj

**Comment by mozmorris** [comment]
@LKay can you you supply some example code?

**Comment by dennis-8** [comment]
This is how to show both cameras on iPhone:

https://codepen.io/dennis888/pen/poRqQgN

**Comment by jomadjambe** [comment]
@LKay or @mozmorris this package seems to working fine on desktop for me on my local but not having any luck on my iPhone 12? Is the reason for this because my app isn't running over HTTPS?  

P.S: I tried implementing the code example provided by @dennis-8 still not working for me

**Comment by mozmorris** [comment]
Does the demo work? https://codepen.io/mozmorris/pen/JLZdoP

**Comment by jomadjambe** [comment]
When running on desktop yes the demo does work but running it on my iPhone am getting the following error: 
navigator.mediaDevices.enumerateDevices is not a function

**Comment by mozmorris** [comment]
@jomadjambe sorry for the slow response. I don't suppose you are using Chrome on Mobile?
