### ISSUE TITLE
How to mute the beep sound in starting and in ending, while recording video from webcam in browser in react.

### ISSUE THREAD

**Issue by codercoder12** [mozmorris/react-webcam#253]
## Please follow the general troubleshooting steps first:

- [ ] Is your app running over HTTPS? (please provide the URL if possible)
- [ ] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [ ] Checked the latest "Can I use" compatbility table? (https://caniuse.com/stream)

### Bug reports:

If you can provide a minimal reproducible demo (CodePen, CodeSandbox, etc) or a GitHub repository, that will greatly help us to solve your problem. Many of the issues posted are questions about react-webcam usage. We don't discourage you posting a question, it's just a lot easier to help you if we can see your code.

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by codercoder12** [comment]
While using react-webcam to record video and audio from a browser(chrome), then when we play that recorded video there a beep sound(sounds like a button is clicked) in starting of the video and in ending of the video. how can we mute/remove the beep sound from the recorded video. I used the recording demo, everything works fine but there is a beep sound in starting and ending of the recorded video.

**Comment by mozmorris** [comment]
@codercoder12 have you tried disabling the `audioConstraints` ? 

```jsx
<Webcam audioConstraints={false} />
```

Could you post a sample of the video?

**Comment by codercoder12** [comment]
This is muting everything, even what we are speaking. How can we enable audio but disable that beep sound(clicking button sound) ?

**Comment by mozmorris** [comment]
What sort of Webcam are you using @codercoder12?

**Comment by codercoder12** [comment]
I am using macbook's camera for recording video in browser

**Comment by mozmorris** [comment]
Is there an possibility you could send me a sample? I have tested here on a MacBook and I don't get a beep. I wonder what is causing that.

**Comment by mozmorris** [comment]
@codercoder12 if this issue is resolved would you mind leaving a comment here just in case another developer experiences the same issue?

**Comment by codercoder12** [comment]
Issue was because of me, I was using mouse to press start and stop(it was next to my laptop's mic), it was creating a beep sound. I then changed to trackpad then it was fine.
