### ISSUE TITLE
React webcam is not detecting camera which is connected by IP address

### ISSUE THREAD

**Issue by bhushan90** [mozmorris/react-webcam#254]
I have integrated react-webcam in my application.
It is working fine for the system camera.

But I need to connect it to my IP camera.

In the device list, I can not get the IP attached camera name and Id.

**Comment by mozmorris** [comment]
@bhushan90 thanks for posting this.

Could you clarify if this is a react-webcam issue or that you can't get access to the camera at all?

Could you check that your device is listed here: https://webrtc.github.io/samples/src/content/devices/input-output/

**Comment by bhushan90** [comment]
@mozmorris  Thank you for the quick response.
I am not sure as the issue is reported by the client.
But could please tell me if **react-webcam** detects the camera connected by IP or not?
As some users facing issues while detecting IP cameras on their side.

**Comment by mozmorris** [comment]
This component doesn't do any detection as such. It's a wrapper around `getUserMedia`. If `getUserMedia` or `enumerateDevices` can't detect the camera, then you're out of luck I'm afraid.

**Comment by bhushan90** [comment]
Yes, I think getUserMedia doesn't detect IP cameras.

Thank You So much.
