### ISSUE TITLE
How can click multiple screenshots ?

### ISSUE THREAD

**Issue by BradPrit09** [mozmorris/react-webcam#256]
## Please follow the general troubleshooting steps first:
- [x]  App running over http://localhost:8000/
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [x] Checked the latest "Can I use" compatbility table? (https://caniuse.com/stream)

### Question:
I have been trying to get multiple screenshots but I am stuck. There is no documentation regarding this issue. Is there a feature to get multiple screenshots ?

The code sample I have used is : https://codepen.io/mozmorris/pen/gOOoqpw 

@mozmorris

**Comment by mozmorris** [comment]
Hi @BradPrit09 - can you supply a demo of what you've tried so far?

**Comment by BradPrit09** [comment]
Hi @mozmorris  I have used this as an example and getting only the current screenshot.
```

const WebcamCapture = () => {
  const webcamRef = React.useRef(null);
  const mediaRecorderRef = React.useRef(null);
  const [imgSrc, setImgSrc] = React.useState(null);
  const [capturing, setCapturing] = React.useState(false);
  const [recordedChunks, setRecordedChunks] = React.useState([]);

  const capture = React.useCallback(() => {
    const imageSrc = webcamRef.current.getScreenshot();
    setImgSrc(imageSrc);
  }, [webcamRef, setImgSrc]);



  return (
    <>
      <Webcam
        audio={false}
        height={284}
        width={554}
        ref={webcamRef}
        screenshotFormat="image/jpeg"
        screenshotQuality={1}
        minScreenshotHeight={110}
        minScreenshotWidth={137}
      />
      {imgSrc && (
        <img
          alt="Captured"
          src={imgSrc}
        />
      )}
      <button type="button" style={{ border: "none" }} onClick={() => capture()}>
        <CameraIcon />
      </button>
    </>
  );
};
```

**Comment by BradPrit09** [comment]
Can anyone guide me here ?
@mozmorris  !

**Comment by mozmorris** [comment]
@BradPrit09 you will need to put your captured screenshots in an array or object.

**Comment by mozmorris** [comment]
Like so https://codepen.io/mozmorris/pen/LYRjOdj

**Comment by BradPrit09** [comment]
Thank you very much. @mozmorris

**Comment by BradPrit09** [comment]
Can I show recorded videos as a preview ?
