### ISSUE TITLE
How can we apply zooming into camera on mobile decvices.

### ISSUE THREAD

**Issue by bhushan90** [mozmorris/react-webcam#257]
Is there any way to apply zooming on mobile devices?

I have added react-webcam in my application.
The camera is working on mobile devices.
ut now I want to zoom into the camera so that I can capture images from a long distance.

**Comment by mozmorris** [comment]
@bhushan90 I guess there's a couple of ways of looking at this, 

1. Physically trying to zoom the camera (if the device has a telephoto lens), 
or 2. Cropping the image and enlarging it (much like how cameras without telephoto lens works)

I'm not sure 1 is possible. I can't find anything in the web spec.
2. You would need to handle this yourself.

**Comment by wobsoriano** [comment]
Zooming reference https://web.dev/articles/camera-pan-tilt-zoom
