### ISSUE TITLE
Show recorded videos as a preview .

### ISSUE THREAD

**Issue by BradPrit09** [mozmorris/react-webcam#258]
Can I show recorded videos as a preview ?
Code sample : https://codepen.io/mozmorris/pen/yLYKzyp?editors=0011

_Originally posted by @BradPrit09 in https://github.com/mozmorris/react-webcam/issues/256#issuecomment-752195991_

**Comment by mozmorris** [comment]
@BradPrit09 closing as this is outside the remit of react webcam.
