### ISSUE TITLE
Adding an audio analyzer to webcam

### ISSUE THREAD

**Issue by Nitzahon** [mozmorris/react-webcam#259]
Hi there.  What I'm trying to do is to connect a basic audio analyzer to the webcam stream, in order to be able to call a function when it goes over the threshold.  (example for context: [audio analyzer](https://jsbin.com/uCalijA/2/edit?html,css,js,output) just without the face) In the end, I want the users voice to trigger a voice recognition component I have, my main issue is how do I connect such a thing to the webcam?

**Comment by mozmorris** [comment]
@Nitzahon the `onUserMedia` prop callback is passed the media stream. You could pass this to your `createMediaStreamSource` method.

**Comment by Nitzahon** [comment]
This really helped, though audio analyzer was a dead-end.  I found a perfect solution: https://www.npmjs.com/package/hark, connected it to the webcam stream, and connected functions to trigger on speaking and stopped_speaking.  Highly recommended
