### ISSUE TITLE
Some versions of macbook m1 when i start recording It only shows the loader.

### ISSUE THREAD

**Issue by ehsantekgenisys** [mozmorris/react-webcam#266]
Some versions of macbook m1 when i start recording all i can see is loading icon. 

it is working fine for safari(if i enable media recorder from experimental feature) But for chrome and safari its showing loader icon.

I am adding a screen recording here to better explain the problem i am facing

https://user-images.githubusercontent.com/34641203/106059024-e473cf80-6113-11eb-8b3c-f73e8a024b98.mov

**Comment by mozmorris** [comment]
@ehsantekgenisys can you share some of your code?

**Comment by ehsantekgenisys** [comment]
@mozmorris I figured out the issue i had epocam installed.

 The problem was with react-webcam is it selects third party webcam by default when i start recording.

I tried uninstalling epocam and it worked. 

This may happen with other users as well when they have third party library installed. 

I am adding a link for epocam. Incase you want to investigate it.
 https://www.elgato.com/en

**Comment by mozmorris** [comment]
@ehsantekgenisys I suggest giving your users a list of devices to select from. react-webcam doesn't make any choices or default to a device here - it simply does what getUserMedia does.
