### ISSUE TITLE
How to mirror video recording?

### ISSUE THREAD

**Issue by codercoder12** [mozmorris/react-webcam#271]
## Please follow the general troubleshooting steps first:

- [x] Is your app running over HTTPS? (please provide the URL if possible)
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [x] Checked the latest "Can I use" compatbility table? (https://caniuse.com/stream)

### Bug reports:

How can we mirror recorded video, I am passing mirrored={true} as prop, it mirrors the webcam component but when I view that recording it is not mirrored.

**Comment by mozmorris** [comment]
@codercoder12 you will need to mirror your stream. The mirror prop in this case only affects the video elements and if you take a screenshot.

**Comment by codercoder12** [comment]
The stream is being passed to media recorder API 
```
mediaRecorderRef.current = new MediaRecorder(webcamRef.current.stream, {
        mimeType: "video/webm;codecs=H264"
      });
```

How can I mirror this stream?

**Comment by mozmorris** [comment]
I believe it's possible to get a stream from a canvas element. I've not actually tried it before. Take a look at https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/captureStream for details.

The approach would be something like:

1. Render stream to canvas
2. Flip/Mirror canvas
3. Capture stream from canvas

Best of luck!

**Comment by bilinkis** [comment]
Having the same problem here. Any way to mirror the stream?
