### ISSUE TITLE
Blank On First Render - Samsung s10+/Note8 (Chrome)

### ISSUE THREAD

**Issue by RodolfoSarkisRocha** [mozmorris/react-webcam#274]
## Please follow the general troubleshooting steps first:

- [x] Is your app running over HTTPS? (please provide the URL if possible)
- [x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [x] Checked the latest "Can I use" compatbility table? (https://caniuse.com/stream)

Hi, I'm having trouble opening the component in mobile chrome, it works fine in my desktop with my webcam, but when I open the webcam in the mobile, it returns no video stream on screen, it also asks for permission and all, but nothing happens after. 

I've also run codepen in my device (samsung s10+) and another one (samsung note8) and the result remains blank until I close the browser and come back to it or if render the component again.

This is my code: 
None of the components are hiding the camera, since it appears normally in the desktop web.
I'm asking for permission using a customHook I made using getUserMedia({video: true, audio false})

```
const videoConstraints = {
    facingMode: frontal ? 'user' : 'environment',
  };

return (
    <>
      <StyledCameraContainer fullscreen={fullscreen}>
        <Webcam
          audio={false}
          onLoadedData={onLoadedData ? () => onLoadedData() : undefined}
          ref={webcamRef}
          screenshotFormat="image/jpeg"
          videoConstraints={videoConstraints}
          forceScreenshotSourceSize
        />
        <StyledCloseButton
          portrait={landscape === false}
          onClick={exitCallback}
        />
        {manualCapture && (
          <StyledButton portrait={landscape === false} onClick={captureFrame}>
            <CameraFilled />
          </StyledButton>
        )}
        {overlay && overlay}
        {error && <StyledWarnMessage>{errorMessage}</StyledWarnMessage>}
        {canvas && <StyledCanvas ref={canvasRef} />}
      </StyledCameraContainer>
    </>
  );
```

**Comment by ProtoCh4os** [comment]
Doing some research, I decided to try this solution found on the README.md: https://github.com/mozmorris/react-webcam#show-all-cameras-by-deviceid

```
  const [deviceId, setDeviceId] = React.useState({});
  const [devices, setDevices] = React.useState([]);

  const handleDevices = React.useCallback(
    mediaDevices =>
      setDevices(mediaDevices.filter(({ kind }) => kind === "videoinput")),
    [setDevices]
  );

  React.useEffect(
    () => {
      navigator.mediaDevices.enumerateDevices().then(handleDevices);
    },
    [handleDevices]
  );
```

Manually passing the devideId gotten from `handleDevices` to the `videoConstraints` prop did the trick, and now it is working well on mobile (Even as a PWA)

Hope this solution helps!

**Comment by mozmorris** [comment]
@RodolfoSarkisRocha thanks for posting this issue, and to @ProtoCh4os for some potential help.

Due to working from home, I don't have access to any of the devices you listed currently. Just for the sake of testing the most basic non-react example, could you test your device(s) with the following example? https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Comment by RodolfoSarkisRocha** [comment]
Hi!

Sorry for the delay.
I found a solution in the mean time, the thing is, my hook was asking permission the wrong way. 

What solved the issue was using this as constraints: 

```tsx
{
    video: { facingMode: 'environment' },
    audio: false,
}
```

Thanks for all the atention!
