### ISSUE TITLE
MediaStreamError after several refreshing page or returning back from other pages

### ISSUE THREAD

**Issue by Aliaksandr-Yanushkevich** [mozmorris/react-webcam#276]
## Please follow the general troubleshooting steps first:

- [X] Is your app running over HTTPS? (https://takepic.netlify.app/)
- [X] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [X] Checked the latest "Can I use" compatbility table? (https://caniuse.com/stream)

### Bug reports:
Actual result:
I get MediaStreamError after several refreshing page or returning back from other pages.
Code example: https://codepen.io/aliaksandr-yanushkevich/pen/wvodBOZ
Video example: https://www.loom.com/share/10f189855c17429881ac09dac54a220d
Deploy: https://takepic.netlify.app/ (login: test@belarus.by, pass: Test@123)

Expected result:
camera works without error

**Comment by mozmorris** [comment]
@Aliaksandr-Yanushkevich thank for reporting this and the links, very helpful.

I logged in to the app with the username & password, followed you steps, but for me I can refresh many times without seeing the error.

I wonder if it might be an issue with your device. Perhaps it doesn't like being enabled quickly in succession. Do you see any errors in the console when it fails?
