### ISSUE TITLE
Video toggle on and off

### ISSUE THREAD

**Issue by jdeboi** [mozmorris/react-webcam#277]
### Features:

Sorry if this is obvious—I want to be able to toggle the webcam on and off with a button click (like Zoom), and I'm not sure if I'm doing this correctly. Currently I'm selectively rendering <Webcam /> based on a button state, e.g.

```
{videoOn?<Webcam audio={audioOn} videoConstraints={videoConstraints} />:null}
```

I'm pretty sure that when the <Webcam /> component disappears from the parent component that the stopAndCleanup() method gets called. I just wanted to double check that this is the appropriate way to toggle the video, and that I'm not inadvertently creating multiple instances of the webcam or some other issue. If you thought it made sense, I think a mention in the documentation would be super helpful. Thank you!!

**Comment by mozmorris** [comment]
@jdeboi yes that's exactly how it should work.

A couple of examples using two different methods:
https://codepen.io/mozmorris/pen/PBezdq
https://codepen.io/mozmorris/pen/pojYEPR

Documentation PRs always welcome :-)
