### ISSUE TITLE
not working with google chrome in macbook pro

### ISSUE THREAD

**Issue by buncis** [mozmorris/react-webcam#281]
not even the codepen example works https://codepen.io/mozmorris/pen/pojYEPR
it just give blank/white page not even asking for permission

macOS Big Sur
Version 11.2.3
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Google Chrome Version 89.0.4389.90 (Official Build) (x86_64)

it works with safari/opera

**Comment by mozmorris** [comment]
@buncis thanks for posting this. Let's try to figure out why this is happening....

Firstly, could you check your privacy settings in System Preferences. Is your Chrome allowed to access your camera?

<img width="667" alt="Screenshot 2021-03-21 at 09 15 18" src="https://user-images.githubusercontent.com/156303/111899704-22abb200-8a26-11eb-99c8-cb82e351c795.png">

**Comment by buncis** [comment]
<img width="675" alt="Screen Shot 2021-03-21 at 16 27 24" src="https://user-images.githubusercontent.com/14258779/111899959-53114180-8a62-11eb-8a6f-25043cf91e45.png">

can you confirm if this not working on your mac too? or its just me ?

**Comment by mozmorris** [comment]
Yes it works fine here.

Next, could you check the console for any errors? (both the Codepen console and your devtools console)

And also try this non-React example: https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Comment by buncis** [comment]
damn you are really good even u work for bug that only happen to me

here is the result for non-react example

from the page

```
getUserMedia error: NotFoundError

Warning: if you're not using headphones, pressing play will cause feedback.
```

the console
```
DOMException: Requested device not found
errorMsg @ main.js:41
```

**Comment by mozmorris** [comment]
<img width="1072" alt="Screenshot 2021-03-21 at 09 41 05" src="https://user-images.githubusercontent.com/156303/111900293-99967a00-8a29-11eb-8214-0d9d979e8bfb.png">

<img width="703" alt="Screenshot 2021-03-21 at 09 41 11" src="https://user-images.githubusercontent.com/156303/111900295-9dc29780-8a29-11eb-92b6-a745a92a457f.png">

In Chrome settings -> `Privacy and security` -> `Site settings` -> `Camera`

**Comment by buncis** [comment]
there is no FaceTime HD Camera in that one, and I have that I my opera I think that is the culprit

**Comment by mozmorris** [comment]
Aha! That would probably be the issue.

**Comment by buncis** [comment]
![Screen Shot 2021-03-21 at 16 46 38](https://user-images.githubusercontent.com/14258779/111900403-02e7ae80-8a65-11eb-9d9c-3b1a5931be30.png)

**Comment by mozmorris** [comment]
Try closing all your other browsers and restarting Chrome.

**Comment by buncis** [comment]
I've tried that before opening this issue

to fix this you need to toggling your chrome privacy settings in here 
![image](https://user-images.githubusercontent.com/14258779/111900500-7a1d4280-8a65-11eb-8ceb-e2da3dccd654.png)


@mozmorris what a fast response ma dude thank you so much for helping me through this!

**Comment by mozmorris** [comment]
Yay!!
