### ISSUE TITLE
Camera getting hanged in the android 11 based samsung f41 phone

### ISSUE THREAD

**Issue by sunilkhuwal** [mozmorris/react-webcam#284]
## Please follow the general troubleshooting steps first:

- [x] Is your app running over HTTPS? (please provide the URL if possible)
- [ ] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [x] Checked the latest "Can I use" compatbility table? (https://caniuse.com/stream)

### Bug reports:

hey Team, I am trying to capture the photo, in the Android 11 based Samsung F41 phone, and it gets hanged.
The same feature I tried to run the same scenarios in the IPhone 8 and there it was working fine.

I tried to pull down the resolutions by reducing the number in `screenshotQuality` to .1 but still phone get hanged.

Pls advice.

**Comment by itb2k13** [comment]
@sunilkhuwal are you using Chrome on Android 11? 

If so, note there is a more general bug with media access and Chrome on Android 11 being tracked here -> https://issuetracker.google.com/u/1/issues/173142922

Hopefully the Chrome developers will fix the hanging problem in v90 (it is also affecting our project quite badly, and for now we've had to disable access for all Chrome + Android 11 users !)

**Comment by sunilkhuwal** [comment]
Many of the users using our web app having the issues for the devices used are Chrome and android 11
I'm hoping for the fix to come early, is there any way this can be fixed? Any pointers that i can refer to.

**Comment by mozmorris** [comment]
Closing in favour of #244
