### ISSUE TITLE
Get device ID of selected webcam

### ISSUE THREAD

**Issue by eox2** [mozmorris/react-webcam#285]
Hi

Is it possible to get the device id and name for the webcam that was selected by the constraints I passed?

I had a brief look at the source code, didn't look like it.

Ex. In the read me, first example where you create the WebcamCapture component & store the webcamRef. Is there any way to know which device id was selected based on the constraints passed? 

Thanks

**Comment by mozmorris** [comment]
@eox2 yes, this should be possible.

One can use the `onUserMedia(stream)` or a ref to get access to the stream.

Haven't tested the following, but it _should_ work:

```js
stream.getVideoTracks()
```
https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/getVideoTracks

From a video track

```js
const track stream.getVideoTracks()[0]
const constraints = track.getConstraints()
const { deviceId } = constraints
```
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getConstraints

**Comment by mozmorris** [comment]
Here's a quick demo: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getSettings

**Comment by eox2** [comment]
Perfect thank you!
