### ISSUE TITLE
Can't record video during voice call error in some devices 

### ISSUE THREAD

**Issue by sedhalsoni** [mozmorris/react-webcam#288]
I'm getting error in some devices like Samsung when I have to try to recording video so getting errors in chrome browser like "Can't record video during voice call".

Please check and let me know if anything any solution to it.

![1620974844736](https://user-images.githubusercontent.com/26431895/118233463-8cd55600-b4af-11eb-866a-e52848751ca8.JPEG)

**Comment by mozmorris** [comment]
@sedhalsoni can you share come code?

**Comment by mozmorris** [comment]
@sedhalsoni looking at your photo, I can see the camera is working. Note, recording isn't built into this component - I'm guess that's a feature of your phone.
