### ISSUE TITLE
Camera View turns blank  in Firefox Browser.

### ISSUE THREAD

**Issue by tittodominic5** [mozmorris/react-webcam#290]
Camera View turns blank when clicking a picture in Firefox Browser.

**Comment by mozmorris** [comment]
@tittodominic5 thanks for posting this. Can you supply some further information like Firefox version, operating system, your example code?

I'd just tested the demo here on Firefox 88.0.1, MacOS - it's working as expected. I do get the option to view as "picture in picture" but this works as well.

**Comment by tittodominic5** [comment]
@mozmorris yes sure. The firefox version is 88.1.3. The OS is Android 10. Also this same issue exist in other android versions also. We tried in many other devices and issue persists. Also we tried in BrowserStack.

**Comment by tittodominic5** [comment]
@mozmorris Please see the code.
<Orientation orientation="landscape" alwaysRender={false}>
          {/* (!isIOS || isMobileSafari) land-scape */}
          <CustomView condition={!isIOS || isMobileSafari}>
            <div className={"camera-view camera-view-offer"}>
              <div className="d-flex justify-content-between">
                <div className="camera-left p-3 d-flex">
                  <div className="d-flex align-items-end mb-4">
                    {!isIOS && !isActiveFullScreen &&
                      <div
                        className={`${isFullScreen ? "normal-screen" : "maximize-screen"}`}
                        id="hidden-btn"
                        onClick={toggleFullScreen}
                      ></div>
                    }
                  </div>
                </div>
                {!capturedImage ? (
                  <div className="camera-mid">
                    <Webcam
                      audio={false}
                      width={videoDimensions.width}
                      height={videoDimensions.height}
                      ref={webcamRef}
                      screenshotFormat="image/png"
                      videoConstraints={{
                        width: { min: 840, ideal: 1920 },
                        height: { min: 360, ideal: 1080 },
                        aspectRatio: { ideal: 1.7777777778 },
                        facingMode: { exact: "environment" },
                      }}
                      screenshotQuality={0.99}
                      forceScreenshotSourceSize
                      onUserMedia={() => {
                        onPermissionAllow();
                      }}
                      onUserMediaError={() => {
                        onPermissionDeny();
                      }}
                    />
                    {showOverlay && (
                      <div className="d-flex align-items-center justify-content-center h-100 px-4 overlay">
                        <img
                          src={`/static/img/${overlay}`}
                          title={`/static/img/${overlay}`}
                          className="img-fluid m-5"
                          width="90%"
                        />
                      </div>
                    )}
                    <div className="text-bar">{title}</div>
                  </div>
                ) : (
                  <div className="camera-mid m-auto">
                    <img
                      src={capturedImage}
                      alt={title}
                      title={title}
                      width={videoDimensions.width}
                    />
                  </div>
                )}
                <div className="camera-right">
                  <div className="d-flex justify-content-around h-100 flex-column align-items-center">
                    {!!capturedImage && (
                      <div className="retake-out">
                        <button
                          type="button"
                          onClick={() => setCapturedImage(null)}
                          className="btn retake-btn"
                        >
                          RETAKE
                        </button>
                      </div>
                    )}
                    {!capturedImage && (
                      <div className="retake-out">
                        <button
                          type="button"
                          onClick={onClose}
                          className="btn retake-btn"
                        >
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                    )}

                    <div>
                      {" "}
                      <button
                        type="button"
                        onClick={!!capturedImage ? save : capture}
                        className="btn circle-btn"
                      >
                        {!!capturedImage && "DONE"}
                      </button>
                    </div>

                    {/* <div>  <button type="button" className="btn btn-dark">RETAKE</button></div> */}
                    <div className="retake-out">
                      {!capturedImage && (
                        <button
                          type="button"
                          className="btn retake-btn"
                          onClick={() => {
                            setShowOverlay((showOverlay) => !showOverlay);
                          }}
                        >
                          <span
                            className={`blue-circle ${!showOverlay && "active"
                              }`}
                          ></span>
                        </button>
                      )}{" "}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </CustomView>
          {/* !(!isIOS || isMobileSafari) */}
          <CustomView condition={!(!isIOS || isMobileSafari)}>
            {!capturedImage ? (
              <section className="screen-center">
                <div className="card-body footer-card m-4 p-4">
                  <div className="row text-center">
                    <div className="col-4 m-auto">
                      <div>
                        <div>
                          {" "}
                          <img
                            src={`/static/img/${overlay}`}
                            title={`/static/img/${overlay}`}
                            className="img-fluid"
                          />{" "}
                        </div>
                      </div>
                    </div>
                    <div className="col-11 m-auto">
                      <h6 className="text-primary py-2 m-0 text-uppercase text-bold">
                        {title}
                      </h6>
                      <p className="text-dark font-italic text-xs text-bold">
                        Please make sure this side of the vehicle is fully
                        visible in the camera.
                      </p>
                    </div>
                  </div>
                  <div className="row justify-content-center m-0">
                    <div className="col-xs-12 col-sm-6  text-center ">
                      <button
                        className="btn btn-lg btn-secondary btn-getoffer w-100 fit-content py-2"
                        onClick={() => {
                          document.getElementById("cam-button")?.click();
                        }}
                      >
                        Continue
                      </button>
                    </div>
                  </div>
                </div>

              </section>
            ) : (
              <div className="camera-view camera-view-offer">
                <div className="d-flex justify-content-between">
                  <div className="camera-left p-3 d-flex">
                    <div className="d-flex align-items-end mb-4"></div>
                  </div>
                  <div className="camera-mid m-auto">
                    <img
                      src={capturedImage}
                      alt={title}
                      title={title}
                      width={videoDimensions.width}
                    />
                  </div>
                  <div className="camera-right">
                    <div className="d-flex justify-content-around h-100 flex-column align-items-center">
                      {!!capturedImage && (
                        <div className="retake-out">
                          <button
                            type="button"
                            onClick={() => setCapturedImage(null)}
                            className="btn retake-btn"
                          >
                            RETAKE
                          </button>
                        </div>
                      )}
                      <div>
                        {" "}
                        <button
                          type="button"
                          onClick={save}
                          className="btn circle-btn"
                        >
                          {"DONE"}
                        </button>
                      </div>
                      <div className="retake-out"></div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </CustomView>
        </Orientation>

**Comment by mozmorris** [comment]
@tittodominic5 is there anyway you could make this into a CodeSandbox or CodePen? Or do you have a dev/qa environment setup somewhere?

There's quite a lot going on in this code - I'd like to try to isolate the issue.

And does the demo (https://codepen.io/mozmorris/pen/JLZdoP) also have the same issue?

**Comment by mozmorris** [comment]
Yes, the demo works here on mobile Firefox too - I suspect then that this is something in your app causing the issue.

Have you tried removing all the logic and other components and simply rendering the Webcam component?

**Comment by tittodominic5** [comment]
Will check that and update that here. The reason i posted the issue was it was fine in chromium based browsers.

**Comment by mozmorris** [comment]
@tittodominic5 did you manage to solve the issue?
