### ISSUE TITLE
How to add a Loader using onUserMedia?

### ISSUE THREAD

**Issue by SoneThaya** [mozmorris/react-webcam#291]
I am trying to implement a loading spinner while the webcam is turning on. I used a ternary operator to check if showLoader is true. It works but it appears the webcam is turning on and off four times. I believe it is because I am using the Webcam component two different times. Is there a better way I could do this to add a loading spinner before the webcam is on? thanks in advance.

```
handleUserMedia = () => {
        this.setState({ showLoader: false });
    };

this.state.showLoader ? (
                 <div>
                     <Loader />
                     <p>Starting Camera...</p>
                     <div className="loading-webcam">
                          <Webcam onUserMedia={this.handleUserMedia} />
                     </div>
                 </div>
            ) : (
                 <>
                    <Webcam
                           audio={false}
                           height={365}
                           ref={this.setRef}
                     />
                  </>
             )}
```

**Comment by mozmorris** [comment]
As a basic idea: https://codepen.io/mozmorris/pen/poeRNWb?editors=0010

**Comment by SoneThaya** [comment]
Thank you!
