### ISSUE TITLE
Webcam not shutting down after component unmounted. 

### ISSUE THREAD

**Issue by pawan-khade** [mozmorris/react-webcam#292]
I have used component in my project. When this component is unmounted web cam light in laptop remains on. following is my code.

function  WebCamCapture (props)
 {
    const webcamRef                         = React.useRef(null);
    const [imgSrc, setimgSrc]               = useState(null);
    const videoConstraints                  = {facingMode: "user"};
    let history                             = useHistory();
    const {setPopupShow,setPopupMsg}        = useContext(PopupContext);
    const exam                              = props.exam;
    const capture1                          = props.capture;

   
    function stop()
    {
      navigator.mediaDevices.getUserMedia({video: true, audio: false})
      .then(stream => 
      {
        const tracks = stream.getTracks();
        tracks.forEach(track => track.stop());
        tracks.forEach(track => track.enabled = false); 
        
      });
    }

useEffect(() => 
    {
          let myInterval = setInterval(() => 
          {
            navigator.mediaDevices.getUserMedia({ video: true, voice: false })
            .then(function(stream) 
            {
                props.setMyCameraPerm(true);
            })
            .catch(function(err) 
            {
                props.setMyCameraPerm(false);
                setPopupShow(true);
                setPopupMsg('Without Camera Premission Examination can not be started.');
                if(currentUser && currentUser.role === 'STUDENT')
                {
                    history.replace('/studenthome');
                }
                else if(currentUser && currentUser.role === 'ADMIN')
                {
                    history.replace('/adminexamreport');
                }
            });
          }, 1000)
          //--------------------------------------------------------------------

          //--------------Cleanup Function--------------------------------------
          return () => {
                    clearInterval(myInterval);
                    stop();
          }
            
    })

return (
      
        <div className="col-lg-12" style={{margin:"20px"}} style={webCamStyle}>
            <center>
                <Webcam
                audio={false}
                height={400}
                ref={webcamRef}
                screenshotFormat="image/jpeg"
                width={300}
                videoConstraints={videoConstraints}
                screenshotQuality={"1"}
                />
            </center>
        </div>
    
    );

}

**Comment by pawan-khade** [comment]
This issue is specifically happening in chrome, chromium, microsoft edge. No problem with mozilla firefox and mozilla family web browsers.

**Comment by mozmorris** [comment]
Thanks for posting this @pawan-khade. Could you create a Sandbox or a CodePen so I can look closer at your issue?

Could you try this example: https://codepen.io/mozmorris/pen/pZVedZ

**Comment by oriasante** [comment]
Hi! I'm having the same error. In my case, I have the webcam component in a modal, and when I close the modal, the camera is still active because I see that the light is still on. Webcam becomes inactive only when I close the window.

I don't have anything defined more than the common use of the webcam component, something like this:

`<Webcam imageSmoothing={true} audio={true} ref={webcamRef} />`

I don't know what could be wrong with my implementation. 

Thanks in advance!

**Comment by oriasante** [comment]
> Hi! I'm having the same error. In my case, I have the webcam component in a modal, and when I close the modal, the camera is still active because I see that the light is still on. Webcam becomes inactive only when I close the window.
> 
> I don't have anything defined more than the common use of the webcam component, something like this:
> 
> `<Webcam imageSmoothing={true} audio={true} ref={webcamRef} />`
> 
> I don't know what could be wrong with my implementation.
> 
> Thanks in advance!

Never mind! Turns out that I wasn't unmounting my modal after all. Thanks anyway!
