### ISSUE TITLE
Is it possible to disable video and leave only audio?

### ISSUE THREAD

**Issue by Nitzahon** [mozmorris/react-webcam#295]
I'm using the webcam to record users talking a survey.  A new use case has arisen where certain people may wish to only be recorded in audio.  I know this seems an odd question to ask for a webcam component, but is there any way to only ask for audio when trying to get user media?  is there perhaps a recommended Mic-only component that I can switch to which uses similar controls to the webcam? something I can switch to in react based on user input?

**Comment by mozmorris** [comment]
@Nitzahon for such a use case I would suggest rolling your own custom code. react-webcam really is pretty simple once you strip away the backwards compatibility code.
