### ISSUE TITLE
specific camera working on firefox and not chrome

### ISSUE THREAD

**Issue by SFoley1** [mozmorris/react-webcam#296]
I have a specific usb camera connected, it works on firefox in codepen but not in google chrome. 

It is the correct version of chrome as per the can I use page. 

My integrated webcam works fine on firefox and chrome, but my custom camera works only on firefox.
The camera I am using is: ToupCam HDMI multi output camera, 
http://www.touptek.com/product/showproduct.php?lang=en&id=272

**Comment by mozmorris** [comment]
@SFoley1 someone report a similar issue a while back. It turned out to be an issue with the process being used by one browser and so a second browser couldn't use it.
