### ISSUE TITLE
Avoid asking permissions automatically

### ISSUE THREAD

**Issue by mateomotriz** [mozmorris/react-webcam#297]
Hallo, I've created a simple login screen, and If the user is correctly authenticated goes directly to one simple page where this nice react-webcam is implemented;

the thing is that the camera permissions are asked when I open the website (in the login page), how could I disable the automatic permissions prompt, and try to ask for them manually if the user is correctly authenticated ¿?

**Comment by mozmorris** [comment]
@mateomotriz it sounds like you are rendering the component even though the user isn't logged in.

You need to add some logic to only render the component once the user is logged in.

```jsx
<>
	{isLoggedIn && (
		<Webcam />
	})
</>

**Comment by mateomotriz** [comment]
you're completely right, thanks a lot for the answer :)
