### ISSUE TITLE
Possible issue with iPhone 7

### ISSUE THREAD

**Issue by kylix31** [mozmorris/react-webcam#309]
I tested the lib with three iPhone 7, but , apparently, it doesn't call the cam... The curious thing is in all others versions of the iPhone (5, 8, X) that I tested, it worked...  Are there a possible workaround?

**Comment by mozmorris** [comment]
@kylix31 could you try running a non-React version on your iPhone 7: https://webrtc.github.io/samples/src/content/getusermedia/gum/
