### ISSUE TITLE
Play/pause button appear on the webcam viewer, but didn't do anything and then disappear when tapped. Device details: iPhone SE (1st gen), iOS 14.2, Safari 14.

### ISSUE THREAD

**Issue by amerfathullah** [mozmorris/react-webcam#318]
I'm currently working on a project where user need to capture a QR code image and the program will validate if it's matching or not in the database. I only encounter this problem after the QR code is unmatched and the app will redirect the user to the capture image page. No issue during the first time capturing the image.

**Comment by amerfathullah** [comment]
nvm, I got it. need to set the webcam ref to null before redirect to capture image page.

**Comment by viswongdev** [comment]
Mine will disappear while the is player but I want to get rid off entirely, could you tell me more how how you do it?

**Comment by amerfathullah** [comment]
@viswongdev I did useRef for the webcam and init it to null. when clicking the button to redirect to another page, I just reset the ref to null
