### ISSUE TITLE
Disable WebCam untill I want to use it.

### ISSUE THREAD

**Issue by DeanVanGreunen** [mozmorris/react-webcam#320]
Hi, so regarding WebCam.

```
<div ref={this.ui1}>
    <Webcam screenshotFormat="image/jpeg" audio={false} height={232} width={480} videoConstraints={{width: 1280,height: 720,facingMode: "user"}} id="someUniqueIDHere" ref={this.ui1webcam}></Webcam>
</div>
```

thats the example element I have, however its hidden via the ref `this.ui1` by using `this.ui1.current.style.display = "none";`

however when this code is run it directly access the WebCam Stream and shows the recording Icon in the browser tab. see image
![image](https://user-images.githubusercontent.com/22296075/137764911-cf1773ad-49d5-4199-b45e-53968f44e670.png)

now what I would like is if there is a wait to stop/start the stream, so that I can manage when the webcam feed will be accessed, thanks in advance

**Comment by mozmorris** [comment]
I would recommend mounting the <Webcam /> once you need it.

```jsx
// your logic here to set isVisible
const isVisible = true

return (
	<div>
		{isVisible && <Webcam />}
	</div>
)
```

**Comment by malavshah9** [comment]
@mozmorris  Still I will need ref to start and stop recording video as per this example:

https://codepen.io/mozmorris/pen/yLYKzyp?editors=0010

**Comment by DeanVanGreunen** [comment]
@malavshah9 The reason behind my original question was that i only wanted the webcam element to be active when I wanted to use it inorder for it to not access the webcam till required. anyway i have created a work around in my project to support my indended solution
