### ISSUE TITLE
doesnt ask permission on mobile (safari, ios 15)

### ISSUE THREAD

**Issue by cupof2** [mozmorris/react-webcam#324]
doesnt ask permission on mobile (safari, ios 15)

**Comment by mozmorris** [comment]
@cupof2 can you provide some code? or perhaps a link to your application?

**Comment by cupof2** [comment]
```
import React from 'react';
import Webcam from 'react-webcam';
// import axios from 'axios';

const videoConstraints = {
  facingMode: 'environment',
  width: 1080,
  height: 720,
};

const Camera = () => {
  const webcamRef = React.useRef(null);

  const capture = async () => {
    const image = webcamRef.current.getScreenshot();
    console.log(image);

    // await axios.post('/hi', {
    //   data: image
    // })
  };
  // decode:
  /**
   * var image = new Image();
   image.src = image;
   document.body.appendChild(image);
   */

  return (
    <div>
      <Webcam
        audio={false}
        ref={webcamRef}
        screenshotFormat="image/jpeg"
        screenshotQuality={1}
        videoConstraints={videoConstraints}
      />
      <button onClick={capture}>Capture</button>
    </div>
  );
};

export default Camera;

```
When this component is rendered, it asks for camera permission on desktop but not on mobile

**Comment by mozmorris** [comment]
Does the demo work for you? codepen.io/mozmorris/pen/jlzdop

**Comment by timothymiller** [comment]
> Does the demo work for you? codepen.io/mozmorris/pen/jlzdop

Demo works for me on iPad iOS 15

**Comment by mozmorris** [comment]
@cupof2 have you got a link to your application? Did you read the issue guide before posting? For example, if you application being served over https?

The code supplied looks like one of the demo's created on Codepen, which leads me to think you're hosting this locally and probably not using https.

**Comment by cupof2** [comment]
Yes, I am hosting locally. Could that be the reason why?

**Comment by cupof2** [comment]
I do not have a production link at the moment.

**Comment by mozmorris** [comment]
@cupof2 yes - this is stated when you open a new issue and at the top of the README. I don't know if this is exactly your problem but it usually is for most people. 

---

<img width="795" alt="Screenshot 2021-11-22 at 09 56 36" src="https://user-images.githubusercontent.com/156303/142840655-4830d403-4961-4d0f-93f4-27ecbd9287b7.png">

---

<img width="683" alt="Screenshot 2021-11-22 at 09 57 27" src="https://user-images.githubusercontent.com/156303/142840759-9bb4cddb-8875-4d04-b792-ef254299cd97.png">

---

Taking time to read the guide and the contributing instructions takes a couple of minutes. Unfortunately in my experience a lot of developers are far too quick to open an issue. I can usually spot these types as their issues only contain a single sentence with no other information.

Please don't take this personally, you're not alone.
