### ISSUE TITLE
making react-webcam responsive for mobile

### ISSUE THREAD

**Issue by furkandindar** [mozmorris/react-webcam#327]
I am trying to build an app using react-webcam. This app needs to be mobile responsive. I use Material UI Grid to make it responsive, <Webcam/> always overflows and causes a horizontal scroll on mobile browsers. Is there a way to handle this? Thanks in advance!

`<Grid container>
          <Grid item xs={12} sm={8} md={6} lg={6} xl={6} style={{background:"green"}}>
            <WebcamCapture/>
          </Grid>
  </Grid>`

here, Grid's green background fits in the mobile browser perfectly but WebcamCapture overflows it.

**Comment by mozmorris** [comment]
You will need to apply styling to the <Webcam /> component using the `style` prop, a starting point would be something like:

```jsx
<Webcam style={{ width: "100%" }} />
```
