### ISSUE TITLE
Camera / audio source selection feature

### ISSUE THREAD

**Issue by 7kfpun** [mozmorris/react-webcam#34]
Do you have a plan for this feature? Thanks!

**Comment by MarinusDR** [comment]
I think many are interestet in a possibility to choose which camera to use. Now you only can take 'selfies'. :-)

**Comment by pkpp1233** [comment]
+1

**Comment by AlexandreKilian** [comment]
you can actually select the media device like this:
`<Webcam audioSource={settings.audioDevice} videoSource={settings.videoDevice} />`

**Comment by mozmorris** [comment]
@AlexandreKilian is right but it's not documented.

- [ ] Add audioSource & videoSource props to readme.
