### ISSUE TITLE
[Question] Camera status and LED is on in the browser tab even though the component is unmounted.

### ISSUE THREAD

**Issue by haresh6x** [mozmorris/react-webcam#349]
I am using react-webcam with reference to this codepen source: https://codepen.io/mozmorris/pen/yLYKzyp?editors=0010

But when the component is unmounted, camera status and LED is still on until the tab is closed. I went through the documentation but couldn't find any reference for the same.

How do I fix it?

**Comment by mozmorris** [comment]
Does this example work? https://codepen.io/mozmorris/pen/PBezdq

**Comment by haresh6x** [comment]
> Does this example work? https://codepen.io/mozmorris/pen/PBezdq

Thank you!
