### ISSUE TITLE
[Feature Request] Show video mirrored but take a non-mirrored screenshot

### ISSUE THREAD

**Issue by frankgalindo** [mozmorris/react-webcam#354]
Hi guys, I was working on a project using _react-webcam_ and at some point I needed to show the video mirrored, but take a non-mirrored screenshot. I managed to implement this in my project, but I think that could be a built-in option into the library itself.

I have never contributed to an open source project before, but I would like to implement this feature. Is that OK?

**Comment by SanthoshRaju91** [comment]
@frankgalindo would like to know how you did this. Did you draw the image on a canvas and transformed the scaleX value to get non-mirrored screenshot ?

**Comment by mozmorris** [comment]
@frankgalindo @SanthoshRaju91 is this the functionality you describe? https://codepen.io/mozmorris/pen/oNygXwz

**Comment by mozmorris** [comment]
@frankgalindo thank you for raising this. As it's a case of adding a single line of css, I think it would make sense to add this to the README instead.

```css
video {
  transform: scaleX(-1);
}
```

**Comment by frankgalindo** [comment]
So, should it be an example like "Show all cameras by device Id" or "Recording a stream"?

**Comment by mozmorris** [comment]
@frankgalindo that would be excellent.

**Comment by frankgalindo** [comment]
@mozmorris I just submitted a PR

#355
