### ISSUE TITLE
not asking for permission (chrome only)

### ISSUE THREAD

**Issue by rattkin** [mozmorris/react-webcam#377]
- [ x] Is your app running over HTTPS? (Sorry can't give out the link it's behind a sign-in wall.)
- [ x] Have you tried running the demo (https://codepen.io/mozmorris/pen/JLZdoP) on your device?
- [ x] Checked the latest "Can I use" compatbility table? (https://caniuse.com/stream)

When I run the app during development (`react-scripts start`), it all works fine.

However when I commit the code and deploy it to production, the webcam does not ask for permission when using Chrome and the element is empty `<video autoplay="" playsinline=""></video>`.

The error returned from `onUserMediaError` is `{}` - can I do something to debug it? We tried Mac, Windows, Linux, Android operating systems. Always chrome has problem and other browsers work.

It works in Firefox and Safari, I guess it can be a chrome bug?.

if I enumerate video devices ` navigator.mediaDevices.enumerateDevices()` I get one `videoinput` device, but with no data:

```
{
    "deviceId": "",
    "kind": "videoinput",
    "label": "",
    "groupId": ""
}
```

**Comment by jroeglin** [comment]
I think we have the same problem with an ionic app on android. In the backend the webapp is rendered in a chrome using the webView API of android. All of our packages that use the mediaDevices API seem to have the issue.  I will search the chrome forum, maybe the problem is known.

**Comment by rattkin** [comment]
The problem was not react-webcam.
It was caused by server headers
