### ISSUE TITLE
IE11 compatibility

### ISSUE THREAD

**Issue by ettaibi** [mozmorris/react-webcam#38]
how can i use react-webcam for IE 11 ?

**Comment by ctrlplusb** [comment]
It is up to the browsers I believe.

http://caniuse.com/#search=webcam

You will need to check the capabilities of user's browsers before exposing this feature to them.

**Comment by ctrlplusb** [comment]
I recommend https://modernizr.com/

**Comment by mozmorris** [comment]
There's the potential to use a polyfill here. Closing for now but if there's significant demand, we can reopen and implement.

**Comment by akshaypjoshi** [comment]
Is it implemented?
