### ISSUE TITLE
Constraint Settings

### ISSUE THREAD

**Issue by AlexandreKilian** [mozmorris/react-webcam#40]
Currently, the the options for width/height only affect the rendered canvas, not the video source though. there is no way to set it in the constraints, same goes for other constraints (like echo cancellation, etc...)

**Comment by mozmorris** [comment]
@AlexandreKilian fair point. Moving forward this is something we should add.

**Comment by AlexandreKilian** [comment]
if wanted I can look into a viable solution for this... another example is the microphone quality that is pretty bad with default settings... it's just too bad they made those constraints the way they did

**Comment by mozmorris** [comment]
I'd say hold off until #42 is closed. It's my understanding that the [API has changed](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints). For example, react-webcam is using the video & audio constraint `sourceId` which has been superseded by `deviceId`.

**Comment by cliener** [comment]
As a quick fix - and matching my own requirements - I've added width/height constraints to video in the PR as above. Certainly not the same as, say, opening up the constraints completely but potentially helpful as is.

**Comment by mozmorris** [comment]
Thank again @leeduan.
