### ISSUE TITLE
Update getUserMedia to MediaDevices.getUserMedia()

### ISSUE THREAD

**Issue by hjheath** [mozmorris/react-webcam#42]
https://developer.mozilla.org/en/docs/Web/API/Navigator/getUserMedia is now deprecated.

I can submit a PR if this is still under active development

**Comment by mozmorris** [comment]
@hjheath sorry for the delay. A PR would be fantastic tbh. I noted that change myself. 
My concern is obviously around supporting the new API in older browsers. It would be great if we could handle that too. 

Let me know what you'd like to do.

**Comment by cliener** [comment]
PR created to resolve this. I needed it for my own project to support Safari 11 which only supports the new API.
Tested and working in:
* Chrome 60
* FF 55 & 56
* Safari 11 (no support for the API in earlier versions)
* Edge 15
* IE 11 (no support but handles it correctly)

I created my own namespaced npm version of this library to use it right away https://www.npmjs.com/package/@cliener/react-webcam

**Comment by mozmorris** [comment]
@cliener thanks for this. Get back to you shortly.

**Comment by cliener** [comment]
PR created to resolve this. I needed it for my own project to support Safari 11 which only supports the new API.
Tested and working in:
* Chrome 60
* FF 55 & 56
* Safari 11 (no support for the API in earlier versions)
* Edge 15
* IE 11 (no support but handles it correctly)

I created my own namespaced npm version of this library to use it right away https://www.npmjs.com/package/@cliener/react-webcam

**Comment by mozmorris** [comment]
Closed by #68
