### ISSUE TITLE
Can i select between multiple cameras? Like on a smartphone?

### ISSUE THREAD

**Issue by cbergau** [mozmorris/react-webcam#47]
The title says it all i believe. I want to be able to select between my front- and my backcamera of my smartphone. Am i able to do this with this libary? I have never done any programming with camera, it might be the wrong place to ask.

**Comment by hedinne** [comment]
You can change the video source (camera) by specifying which device should be used. You do this by passing the component a specific `deviceId`.

This will list out all available sources:

`navigator.mediaDevices.enumerateDevices().then(devices => console.log(devices))`

Note that in order for this to work you must pass both audioSource and videoSource. And you can't change sources after react-webcam has mounted.

Hope this answers your question.

**Comment by Vaderico** [comment]
@hedinne You said that you can't change the sources after the react-webcam has mounted. In my application there is a webcam has already mounted, and the user can switch which webcam they want to use mid-use. There is a simple drop down and the webcam feed should change. 

To make things clear - are you saying that to change the video feed we need to un-mount the react-webcam component, and then re-mount it with a different device id? is that the only way to do this?

**Comment by hedinne** [comment]
Hi @Vaderico, sorry for the late replay. It has been so long since I worked with this component so I might be mistaken. But yeah you are correct. 
To fix this I ended forking this project and fixing the bug.

**Comment by ssss1029** [comment]
> Note that in order for this to work you must pass both audioSource and videoSource
I have a video source that does not have a microphone (external camera, plugged in via USB), and when I provide that device's deviceId as a prop, the component does not use it. It falls back to using the `default` camera. Any ideas?
