### ISSUE TITLE
Not working on mobile browsers

### ISSUE THREAD

**Issue by oyeanuj** [mozmorris/react-webcam#48]
Hi @mozmorris, thank you for putting out this library! I was unable to get the demo to work on mobile browsers. It seems like that might be because the origin is considered insecure (since the HTTPS certificate has expired)?

Should it be working on mobile browsers?

**Comment by marco-lavagnino** [comment]
Latest chrome on android works fine (just checked). Try ignoring the https error message.

**Comment by oyeanuj** [comment]
I ignored it but it doesn't work. I am using `iOS` fwiw 😞

**Comment by halvardos** [comment]
This also seems true for safari on OSX

**Comment by mozmorris** [comment]
Yeah, I'm seeing the issue on Safari too. Will attempt to resolve, I'm guessing it's related to #42.

**Comment by BonnieMilian** [comment]
Hi :) I try it on a Android (8.0) Mobile browser (chrome), and is not working, also dont ask for permission.

**Comment by jantonysolstice** [comment]
same as bonnie

**Comment by maverickVision** [comment]
August 2019, still same as Bonnie...

**Comment by mozmorris** [comment]
@maverickVision can you provide some further details? For example, do you have the application running somewhere I can test against? I appreciate it doesn't work for you, but leaving a comment without any extra information won't help us debug the issue.

**Comment by coach-arne** [comment]
hey @mozmorris, I'm having the same issue, but am unable to expose the application... is there any way how I can debug this? It's working on chrome on desktop, but not mobile, so I don't have a stacktrace I can share. The app also did not ask for any permissions.

**Comment by mozmorris** [comment]
Hi @coach-arne - thank you for posting an extra data point for this issue.

Could you tell us the device and browser version?

**Comment by coach-arne** [comment]
I'm trying to get a basic example online, I'll check device data in just a sec :)

**Comment by mozmorris** [comment]
Thanks - we always suggest trying the [demo](https://codepen.io/mozmorris/pen/JLZdoP) on the devices you have.

**Comment by coach-arne** [comment]
I think I've located the issue, it's working on the netlify example, because of the fact that it's **https**. When I'm running react in debug mode it's served as **http**.

Is there a restriction of the underlying browser API (userGetMedia) that it's only working on HTTPS?

**Comment by mozmorris** [comment]
I guessed as much.

Note from the top of the README: `Note: Browsers will throw an error if the page is loaded from insecure origin. I.e. Use https.`

**Comment by coach-arne** [comment]
Always read the manual 😊

**Comment by mozmorris** [comment]
Chrome did used to show a warning which one could bypass. But I thought they had ditched this. The other exception is running the app on localhost.

Over the years this issue has come up a lot, mobile and/or desktop; hence the note right at the top of the README.

**Comment by coach-arne** [comment]
I'm so sorry not reading it though, but I hope everyone gets redirected to this issue and feels just as ashamed as I do 😅

**Comment by mozmorris** [comment]
Hey no worries 👍

**Comment by luizwritescode** [comment]
Update, it is not working on my mobile devices, both android and ios, tested on safari and chrome, however when i run the webpack on a pc it works perfectly

**Comment by mozmorris** [comment]
@luispuig can you try the demo? https://codepen.io/mozmorris/pen/JLZdoP

**Comment by luispuig** [comment]
![D1B41230-CDF5-41E5-AF80-284EACA38528](https://user-images.githubusercontent.com/24297787/79800970-8c769400-835d-11ea-8b21-c80874e617ad.png)

It worked for me. Can you provide  more details to reproduce the problem? 

Not related but the only problems we found were that on Android-Webview there is a bug, get user media seems to work but not. We used the user agent to detect it. Besides, on Facebook Messenger,  there in an extra bug when uploading a file (it is another library but we use it as an alternative of the webcams when fails because the user can pick the native camera)

**Comment by mozmorris** [comment]
What do you mean provide more details to produce the problem? I'm not sure what your problem is, hence asking you to run the demo which works.

**Comment by mozmorris** [comment]
I'm locking this issue since new posts are now missing earlier information. If you come across this thread and are still running into issues after reading through it - please post a new issue.
