### ISSUE TITLE
Multiple webcams support

### ISSUE THREAD

**Issue by jeffbonasso** [mozmorris/react-webcam#54]
Is it possible if I have multiple webcams connected to have multiple Webcam tags, each showing a different webcam? I see the enumerate devices where I could specify the audioSource and videoSource for each one.

**Comment by Vaderico** [comment]
I second this, I would like to know how to make this component support multiple webcams. If we set videoSource equal to an array of device id's, how can we switch between each of those device id's?

**Comment by mozmorris** [comment]
See #47
