### ISSUE TITLE
Doesn't work with iOS 11

### ISSUE THREAD

**Issue by baffleinc** [mozmorris/react-webcam#57]
Hey! Using this component works on Android, however isn't working on iOS 11 Safari. it correctly asks for access to the camera, however I get a Type Error:

![screenshot 2017-09-28 10 18 14](https://user-images.githubusercontent.com/1113588/30943743-5d95ebda-a436-11e7-9126-d81eb0eb0b84.png)

Any ideas? Thanks!

**Comment by cliener** [comment]
I've fixed this by updating the API as part of #42. Since I need it for a project I'm working on, I've added a scoped npm install: https://www.npmjs.com/package/@cliener/react-webcam

**Comment by marlonmantilla** [comment]
hey guys, does this means it will work with IE 11 ?

**Comment by marianobrc** [comment]
Hi, is this issue supposed to be fixed already in the last release? 
I'm having an issue with the cammera in v1.0.4 in iOS 12 in safari and chrome, the cammera component just doesn't work.

**Comment by asaeed** [comment]
+1

would be nice to give us a quick status when closing issues. thanks for the great lib!

**Comment by mozmorris** [comment]
@marianobrc do you see an error?

![img_9084](https://user-images.githubusercontent.com/156303/49538915-64030c80-f8c4-11e8-9291-c69508eb13f2.jpeg)

**Comment by mozmorris** [comment]
@asaeed this was closed by a commit, apologies if that wasn't clear.

**Comment by champion555** [comment]
this component don't work in safari of ios. so i tried to install chrome to confirm it is working in chrome.
but camera did not display in chrome browser. i think it has issue. anyone did fix this issue, please commit it in here.
thanks
