### ISSUE TITLE
MediaStream.stop() is deprecated

### ISSUE THREAD

**Issue by ekitee** [mozmorris/react-webcam#61]
Firefox 56.0 (64-bit) gives this "MediaStream.stop() is deprecated and will soon be removed. Use MediaStreamTrack.stop() instead."
Version 62.0.3202.62 (Official Build) (64-bit) is not warning anyting.

**Comment by cliener** [comment]
I implemented the new API as part of #42. Scoped npm install: https://www.npmjs.com/package/@cliener/react-webcam

**Comment by ekitee** [comment]
Thanks for quick answer.
I am using @cliener version and I am seeing the problem with it (somehow I was not able to report the issue for that project)

**Comment by cliener** [comment]
Since it's a fork, it doesn't have an issue list of it's own.
Here's the code in question - I see what you mean:
```
  componentWillUnmount() {
    const index = Webcam.mountedInstances.indexOf(this);
    Webcam.mountedInstances.splice(index, 1);

    if (Webcam.mountedInstances.length === 0 && this.state.hasUserMedia) {
      if (this.stream.stop) {
        this.stream.stop();
      } else {
        if (this.stream.getVideoTracks) {
          this.stream.getVideoTracks().map(track => track.stop());
        }
        if (this.stream.getAudioTracks) {
          this.stream.getAudioTracks().map(track => track.stop());
        }
      }
      Webcam.userMediaRequested = false;
      this.videoElement.srcObject = null;
    }
  }
```
Feel feel to fix it and I'll integrate into my fork.
