### ISSUE TITLE
navigator.mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by lzmhhh123** [mozmorris/react-webcam#62]
The `navigator.getUserMedia` is not the standard for most browsers. Please use the `navigator.mediaDevices.getUserMedia` to support most of browsers.

**Comment by cliener** [comment]
I implemented the new API as part of #42 with PR pending review. Scoped npm install if you don't want to wait: https://www.npmjs.com/package/@cliener/react-webcam

**Comment by lzmhhh123** [comment]
@cliener OK, Thanks.
