### ISSUE TITLE
Ability to covert the dataURL to File Object or Blob

### ISSUE THREAD

**Issue by aniruddhashevle** [mozmorris/react-webcam#65]
This is a really good package.

We need to add an ability to convert the dataURL to **File Object** or a **Blob** so that we can send the file data using [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) to the backend APIs accordingly.

**Comment by aniruddhashevle** [comment]
@mozmorris : Please tell me how to send the PR. I've forked your repo but there are no instructions to run and make the changes and then replicate the result!

Please let me know the procedure then I'll send the PR. Thanks.

**Comment by mozmorris** [comment]
You have access to the dataUrl.

**Comment by infinityl00p** [comment]
@mozmorris Care to explain how this works? I'm trying to send the screenshot as a file to a server. I'm not sure how that would work with your answer above.

**Comment by aniruddhashevle** [comment]
@infinityl00p : Yes, that's what I did.

**Comment by dahannes** [comment]
@mozmorris What do you think about adding a prop `screenshotDataFormat` which defaults to `base64` but also allows `blob`. That way we could make use of `HTMLCanvasElement.toBlob()` without the need to convert the base64 string afterwards.

**Comment by hasantezcan** [comment]
Thanks

**Comment by hossainrabbi** [comment]
Thanks
