### ISSUE TITLE
Webcam issues on Chrome for android

### ISSUE THREAD

**Issue by tarique93102** [mozmorris/react-webcam#69]
First of all, great library. Kudos to that. I used it in a project. But on Chrome for android, I have come across this issue. After giving the permission to the camera. It is opening the mobile camera sometimes and sometimes it is not. If you want you can have a look at the simple solution I have built.

https://cameria.herokuapp.com

Help in resolving this issue would be super awesome.

**Comment by mozmorris** [comment]
Hello @tarique93102, would you mind testing this again with the latest version (1.4.1)?

**Comment by matheusportela** [comment]
I confirm this is happening to me as well, including in several Android versions and with the current Chrome build 66.0.3359.158. I'll try and gather more info on this issue.

**Comment by mozmorris** [comment]
@matheusportela any details to how I can reproduce? I've been testing on a fairly standard Moto G phone without any issues. 

Do you perhaps have a repo which shows the issue?

**Comment by matheusportela** [comment]
I'm using this component in my company and we'll soon start collecting more info on the devices that fail to open the camera. As soon as I have these data, I'll let you know.

**Comment by massimopibiri** [comment]
Smae problem here. Version 68.0.3440.84 (Build officiel) (64 bits). Not asking for permission and not showing the camera on mobile. Working perfectly on laptop. https well configured.

**Comment by mozmorris** [comment]
@iltoga @massimopibiri I have the latest version on a fairly newish Android phone working here. Are you able to access the dev tools and see if there's any error?

**Comment by massimopibiri** [comment]
the proble really appears just on the mobile phone once online en https. Android 6.0.1

**Comment by massimopibiri** [comment]
Sorry... it was a problem on https configuration.

**Comment by lawanyaselvamani** [comment]
@mozmorris Is this issue get resolved ?
I too facing this issue in chrome Android. Could you please help me to resolve this ?

**Comment by matthewhudgins** [comment]
@massimopibiri what was involved in that https configuration issue?

**Comment by finnmerlett** [comment]
@massimopibiri please if you ever find a solution to a problem, for the love of god just say what it was :sob: I'm also having this issue, would really like to know if you fixed it

**Comment by AHRealift** [comment]
webcam not showing on mobile?
