### ISSUE TITLE
how can i use onUserMedia?

### ISSUE THREAD

**Issue by francisco4challenge** [mozmorris/react-webcam#74]
This hook method has no parameters, what is its use? how can i get the stream to aplly zoom?

**Comment by mozmorris** [comment]
```javascript
import React, { Component } from 'react';
import Webcam from './react-webcam';

class App extends Component {
  handleUserMedia = () => {
    console.log(this.webcam.stream);
  }

  render() {
    return (
      <Webcam
        ref={e => this.webcam = e}
        onUserMedia={this.handleUserMedia}
      />
    );
  }
}

export default App;
```

**Comment by micheldelgallo** [comment]
Hi mozmorris! how can I get all stream data everytime? The WEBCAM component invoke some event always while the cam is on? I would like to stream my webcam online and post the data to the api everytime; The onUserMedia was invoked one time; Thanks
