### ISSUE TITLE
URL.createObjectURL deprecation in July 2018

### ISSUE THREAD

**Issue by Flavien** [mozmorris/react-webcam#76]
Chome gives the following warning when using the package:

> react-webcam.js:217 [Deprecation] URL.createObjectURL with media streams is deprecated and will be removed in M68, around July 2018. Please use HTMLMediaElement.srcObject instead. See https://www.chromestatus.com/features/5618491470118912 for more details.

**Comment by mozmorris** [comment]
Note, the library does handle setting srcObject if the createObjectURL fails.

**Comment by lamuertepeluda** [comment]
@mozmorris wouldn't the converse approach be better? I mean trying createObjectURL if srcObject fails/not supported...

**Comment by TVAO** [comment]
Hi @mozmorris I have used your package but it no longer works on any devices or browsers. It would be awesome if you could change it to use HTMLMediaElement.srcObject instead of using URL.createObjectURL that has now been deprecated. Currently, the Webcam is no longer rendered in the browser.
