### ISSUE TITLE
Support facingMode

### ISSUE THREAD

**Issue by miguelmota** [mozmorris/react-webcam#77]
`MediaTrackConstraints.facingMode` allows you to specify which camera to use in mobile devices

https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode

**Comment by mozmorris** [comment]
Have played around with this a bit but I can't get it to work unfortunately. I'm using iOS in this example.

```javascript
class App extends Component {
  setRef = (component) => {
    this.webcam = component;
  }

  handleUserMedia = () => {
    const videoTrack = this.webcam.stream.getVideoTracks()[0];
    const constraints = videoTrack.getConstraints();
    constraints.facingMode = { exact: "environment" };
    videoTrack.applyConstraints(constraints);
  }

  render() {
    return (
      <Webcam
        ref={this.setRef}
        onUserMedia={this.handleUserMedia}
      />
    );
  }
}
```

The problem I see is that the `MediaTrack` returned by `this.webcam.stream.getVideoTracks()` is a particular camera. Trying to apply the `facingMode` constraint to a particular camera doesn't make sense to me. Clearly it's in the spec so perhaps I'm not "getting it".

The only way I could get it to work was to update the constraints passed to `getUserMedia` e.g.

```javascript
navigator.mediaDevices.getUserMedia({
  video: {
      facingMode: { exact: "environment" },
  },
})
```

...but that would require an update to this library's api. For now, I suggest you pass in the deviceId of the camera you wish to use.

**Comment by mozmorris** [comment]
Okay so I understand this a little better now and will need to work like in my second example. And it's already been mentioned in #40 that React Webcam should support passing in a constraints

**Comment by mozmorris** [comment]
Closing - see #40

**Comment by miguelmota** [comment]
Thanks for looking into this!

Being able to pass in custom constraints would also be ideal.
