### ISSUE TITLE
Dependency error - factoryWithThrowingShims

### ISSUE THREAD

**Issue by jkslyby** [mozmorris/react-webcam#78]
I tried to use your module, but I received the following error:

`error: Resolving deps of node_modules/react-webcam/dist/react-webcam.js failed. Could not load module './factoryWithThrowingShims'`

After some digging, I found someone else with a similar [issue](https://github.com/alibaba/BizCharts/issues/99#issuecomment-357192791).

The solution is to update the webpack config and include prop-types in the externals.

```
externals: [{
    react: {
      root: 'React',
      commonjs2: 'react',
      commonjs: 'react',
      amd: 'react'
    },
    "react-dom": {
      root: 'ReactDOM',
      commonjs2: 'react-dom',
      commonjs: 'react-dom',
      amd: 'react-dom'
    },
    "prop-types": {
      root: 'PropTypes',
      commonjs2: 'prop-types',
      commonjs: 'prop-types',
      amd: 'prop-types',
    }
  }],
```

I cloned your repo and tested it locally and it worked. Do you think you could add this in?

**Comment by mozmorris** [comment]
@jkslyby thanks for this report. Any chance you could provide me with a way to reproduce this error? Perhaps push up a quick repo?

**Comment by mozmorris** [comment]
Actually there's no need. Thanks again for this report.
