### ISSUE TITLE
The webcam doesn't work on aws

### ISSUE THREAD

**Issue by 0oMarko0** [mozmorris/react-webcam#80]
I can't open the webcam if my website is host on AWS ?

**Comment by mozmorris** [comment]
It won't be related to _where_ your application is hosted, more like _how_ it's served. It's almost certainly that your application is running on an insecure origin.

**Comment by 0oMarko0** [comment]
Starting with Chrome 47, getUserMedia() requests are only allowed from secure origins: HTTPS or localhost' 

yes exaclty thanks for the response :)

**Comment by 0oMarko0** [comment]
i didn't use https

**Comment by Im-Goutham** [comment]
Will it not work in http
