### ISSUE TITLE
Better error hint 

### ISSUE THREAD

**Issue by andricicezar** [mozmorris/react-webcam#84]
I spent a few hours to understand why this component was not requesting for permissions to access the webcam, to find out that in Chrome, you can't request for the webcam if the site is not secure.

Error returned by `onUserMediaError`:
```
DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
```

Find out more here: https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features 

Maybe a big hint should be added in the README.md and throw the error anyway, without calling `onUserMediaError`.

**Comment by mozmorris** [comment]
Will add to the readme. Apologies, because this has been covered in various issues in the past.
