### ISSUE TITLE
Support in function getScreenshot save in blob

### ISSUE THREAD

**Issue by MaxAlex666** [mozmorris/react-webcam#87]
Support in function getScreenshot save in blob and qualityArgument.

**Comment by danderson00** [comment]
@MaxAlex666 The workaround for this for now is to use `getCanvas` and then call `toBlob` on the returned canvas. This is essentially what `getScreenshot` is doing - https://github.com/mozmorris/react-webcam/blob/master/src/react-webcam.js#L162

**Comment by mozmorris** [comment]
@danderson00 like this. Agreed, the getScreenshot is just for convenience. The component still offers access to the canvas as well. I'm going to close this.
