### ISSUE TITLE
issue in setRef-module failed

### ISSUE THREAD

**Issue by nchandna** [mozmorris/react-webcam#88]
Please find attach image ,can you @mozmorris  let me know the reason of this error.

below is my app.jsx file
import React from 'react';
import Webcam from 'react-webcam';

class App extends React.Component {

    setRef = (webcam) => {
        this.webcam = webcam;
    }
    capture () {
        const imageSrc = this.webcam.getScreenshot();
        alert(imageSrc);
    };

    render() {
        return(
            <div>
            <Webcam/>
            <button onClick={this.capture}>Capture photo</button>
                </div>);

    }
}
export default App;

Error is:

ERROR in ./App.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: D:/reactApp/App.jsx: Unexpected token (6:11)

  4 | class App extends React.Component {
  5 | 
> 6 |     setRef = (webcam) => {
    |            ^
  7 |         this.webcam = webcam;
  8 |     }
  9 |     capture () {

 @ ./main.js 11:11-31
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./main.js

**Comment by mozmorris** [comment]
Please see https://babeljs.io/docs/en/babel-plugin-transform-class-properties/
