### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [mozmorris/react-webcam#92]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by mozmorris** [comment]
Yeah, why not. 🙂

**Comment by mansya** [comment]
I have design logo for this project. what do you think ? an wich one do you like it ? 

![react webcam](https://user-images.githubusercontent.com/33461607/43599324-6ae6f874-96b1-11e8-9ed0-6cf578f7f558.png)

**Comment by mansya** [comment]
I have upload all file to this link.
https://drive.google.com/open?id=16sWbqJ6m8ZrzhnyceAkLqzqIv2hKEJ4G

And I have sent you [Pull requests.](https://github.com/mozmorris/react-webcam/pull/101) please check it.

**Comment by mozmorris** [comment]
Thank you @mansya !!! 😍
