### ISSUE TITLE
Crashes on Chrome for mobile iOS (both iPad and iPhone)

### ISSUE THREAD

**Issue by BigBrain-AI** [mozmorris/react-webcam#95]
Tested on iOS11 for both iPad and iPhone.

Is there a way to debug on Chrome for mobile iOS? I'll try to post error if it's possible.

**Comment by congdcit** [comment]
It's not support for IOS.

**Comment by ggsjyoon** [comment]
Really? It seems to be supported for iOS11 according to this thou.
https://caniuse.com/#feat=stream

**Comment by FinnFrotscher** [comment]
any update on this?

**Comment by mozmorris** [comment]
@FinnFrotscher nope, still not supported. See https://bugs.webkit.org/show_bug.cgi?id=185448#c6

**Comment by Ciabas** [comment]
How about a note about not supporting IOS on README?

**Comment by mozmorris** [comment]
@Ciabas good suggestion but https://caniuse.com/#feat=stream clearly states it's not supported and this is linked to at the top of the README. It's better imo to use this table as it's kept up to date.

**Comment by josejaguirre** [comment]
Any alternatives ?

**Comment by mozmorris** [comment]
Not yet, still waiting.

**Comment by aniksharif** [comment]
Any update or alternative?
