### ISSUE TITLE
How to turn webcam off?

### ISSUE THREAD

**Issue by AbreezaSaleem** [mozmorris/react-webcam#97]
I dont see any option to turn webcam off. How do I turn it off?

**Comment by mozmorris** [comment]
https://codepen.io/mozmorris/pen/PBezdq?editors=0010

**Comment by wirob** [comment]
Any plans on implementing this?

**Comment by mozmorris** [comment]
Not really, I don't think it's needed imo. You're better off unmounting the component e.g https://codepen.io/mozmorris/pen/pZVedZ?editors=0011
